#!/usr/bin/env python3
"""Generate expanded collocation data for collocation_engine.

Produces texthumanize/_colloc_data.py with compressed collocation data.
Target: 5000+ EN collocations, 1000+ RU, 500+ DE/FR/ES.
"""
import base64
import io
import zlib
import textwrap

# ============================================================
# ENGLISH COLLOCATIONS (~5000+ pairs)
# Curated from corpus linguistics (BNC, COCA patterns)
# Format: (word_a, word_b, pmi_score)
# ============================================================

EN_COLLOCATIONS = [
    # ── Nature / Weather ──
    ("heavy", "rain", 5.2), ("heavy", "snow", 4.8), ("heavy", "fog", 4.3),
    ("heavy", "downpour", 4.6), ("heavy", "frost", 4.2), ("heavy", "dew", 3.9),
    ("heavy", "shower", 4.1), ("heavy", "hail", 4.0), ("heavy", "mist", 3.8),
    ("strong", "wind", 5.1), ("strong", "gale", 4.5), ("strong", "breeze", 4.3),
    ("strong", "current", 4.4), ("strong", "storm", 4.2),
    ("bright", "sun", 4.6), ("bright", "sunshine", 4.5), ("bright", "light", 4.4),
    ("bright", "morning", 4.0), ("bright", "day", 3.9),
    ("thick", "fog", 4.5), ("thick", "cloud", 4.1), ("thick", "smoke", 4.3),
    ("thick", "mist", 4.0), ("thick", "ice", 3.9),
    ("clear", "sky", 4.4), ("clear", "weather", 4.0), ("clear", "day", 3.9),
    ("pouring", "rain", 4.3), ("torrential", "rain", 4.6),
    ("gentle", "breeze", 4.5), ("gentle", "wind", 3.8),
    ("bitter", "cold", 4.4), ("bitter", "winter", 4.1), ("biting", "cold", 4.2),
    ("scorching", "heat", 4.3), ("scorching", "sun", 4.1),
    ("blazing", "sun", 4.2), ("blazing", "heat", 4.0),
    ("driving", "rain", 4.3), ("driving", "snow", 4.0),
    ("howling", "wind", 4.4), ("gusty", "wind", 4.1),
    ("overcast", "sky", 4.2), ("cloudless", "sky", 4.1),
    ("freezing", "cold", 4.3), ("freezing", "rain", 4.0), ("freezing", "wind", 3.8),
    ("sweltering", "heat", 4.2), ("stifling", "heat", 4.1),
    ("dense", "fog", 4.4), ("dense", "cloud", 3.9),
    ("patchy", "fog", 3.8), ("patchy", "cloud", 3.7),
    ("scattered", "showers", 4.0), ("scattered", "clouds", 3.9),
    ("intermittent", "rain", 3.9), ("persistent", "rain", 4.0),
    ("light", "drizzle", 4.1), ("light", "rain", 3.8), ("light", "breeze", 4.0),
    ("steady", "rain", 4.0), ("steady", "wind", 3.8),
    
    # ── Action intensity / Adverbs ──
    ("deeply", "concerned", 4.8), ("deeply", "rooted", 4.6),
    ("deeply", "embedded", 4.3), ("deeply", "committed", 4.4),
    ("deeply", "moved", 4.3), ("deeply", "affected", 4.2),
    ("deeply", "troubled", 4.4), ("deeply", "divided", 4.1),
    ("deeply", "indebted", 4.0), ("deeply", "grateful", 4.1),
    ("deeply", "flawed", 4.2), ("deeply", "personal", 4.0),
    ("deeply", "religious", 3.9), ("deeply", "entrenched", 4.3),
    ("highly", "unlikely", 5.1), ("highly", "likely", 4.8),
    ("highly", "recommended", 4.9), ("highly", "effective", 4.7),
    ("highly", "skilled", 4.8), ("highly", "trained", 4.6),
    ("highly", "competitive", 4.5), ("highly", "successful", 4.5),
    ("highly", "motivated", 4.5), ("highly", "valued", 4.4),
    ("highly", "respected", 4.6), ("highly", "controversial", 4.3),
    ("highly", "profitable", 4.3), ("highly", "qualified", 4.7),
    ("highly", "sensitive", 4.2), ("highly", "influential", 4.4),
    ("highly", "visible", 4.1), ("highly", "regarded", 4.6),
    ("bitterly", "disappointed", 4.7), ("bitterly", "cold", 4.3),
    ("bitterly", "opposed", 4.2), ("bitterly", "divided", 4.1),
    ("bitterly", "contested", 4.2), ("bitterly", "regretted", 4.0),
    ("seriously", "injured", 4.9), ("seriously", "ill", 4.7),
    ("seriously", "damaged", 4.5), ("seriously", "flawed", 4.3),
    ("seriously", "concerned", 4.4), ("seriously", "underestimated", 4.1),
    ("seriously", "considering", 4.3), ("seriously", "threatened", 4.2),
    ("heavily", "influenced", 4.6), ("heavily", "involved", 4.5),
    ("heavily", "armed", 4.7), ("heavily", "dependent", 4.5),
    ("heavily", "indebted", 4.3), ("heavily", "invested", 4.4),
    ("heavily", "taxed", 4.1), ("heavily", "criticized", 4.4),
    ("heavily", "subsidized", 4.2), ("heavily", "regulated", 4.3),
    ("heavily", "polluted", 4.3), ("heavily", "guarded", 4.4),
    ("widely", "known", 4.7), ("widely", "used", 4.8),
    ("widely", "accepted", 4.6), ("widely", "recognized", 4.7),
    ("widely", "regarded", 4.5), ("widely", "available", 4.6),
    ("widely", "criticized", 4.4), ("widely", "spread", 4.3),
    ("widely", "reported", 4.3), ("widely", "believed", 4.5),
    ("widely", "debated", 4.2), ("widely", "discussed", 4.3),
    ("widely", "distributed", 4.3), ("widely", "read", 4.2),
    ("closely", "related", 4.8), ("closely", "monitored", 4.5),
    ("closely", "linked", 4.6), ("closely", "associated", 4.5),
    ("closely", "connected", 4.4), ("closely", "examined", 4.3),
    ("closely", "followed", 4.3), ("closely", "watched", 4.4),
    ("closely", "guarded", 4.3), ("closely", "aligned", 4.2),
    ("closely", "resembled", 4.1), ("closely", "matched", 4.1),
    ("strongly", "recommended", 4.7), ("strongly", "opposed", 4.6),
    ("strongly", "influenced", 4.5), ("strongly", "supported", 4.5),
    ("strongly", "condemned", 4.4), ("strongly", "associated", 4.4),
    ("strongly", "motivated", 4.3), ("strongly", "correlated", 4.5),
    ("strongly", "disagree", 4.4), ("strongly", "believe", 4.5),
    ("strongly", "encourage", 4.3), ("strongly", "suggest", 4.4),
    ("greatly", "appreciated", 4.6), ("greatly", "improved", 4.5),
    ("greatly", "enhanced", 4.4), ("greatly", "increased", 4.3),
    ("greatly", "reduced", 4.3), ("greatly", "influenced", 4.4),
    ("greatly", "benefited", 4.2), ("greatly", "admired", 4.1),
    ("actively", "involved", 4.5), ("actively", "engaged", 4.5),
    ("actively", "participate", 4.4), ("actively", "pursuing", 4.3),
    ("actively", "seeking", 4.3), ("actively", "promoted", 4.2),
    ("actively", "encouraged", 4.2), ("actively", "supported", 4.1),
    ("firmly", "believe", 4.4), ("firmly", "believed", 4.4),
    ("firmly", "established", 4.5), ("firmly", "rooted", 4.3),
    ("firmly", "opposed", 4.2), ("firmly", "committed", 4.3),
    ("firmly", "grounded", 4.1), ("firmly", "convinced", 4.3),
    ("perfectly", "clear", 4.5), ("perfectly", "fine", 4.2),
    ("perfectly", "normal", 4.3), ("perfectly", "acceptable", 4.2),
    ("perfectly", "reasonable", 4.1), ("perfectly", "valid", 4.1),
    ("perfectly", "balanced", 4.0), ("perfectly", "suited", 4.2),
    ("utterly", "ridiculous", 4.4), ("utterly", "useless", 4.2),
    ("utterly", "destroyed", 4.3), ("utterly", "devastated", 4.2),
    ("utterly", "failed", 4.0), ("utterly", "hopeless", 4.1),
    ("utterly", "convinced", 4.0), ("utterly", "impossible", 4.1),
    ("absolutely", "essential", 4.5), ("absolutely", "necessary", 4.4),
    ("absolutely", "certain", 4.3), ("absolutely", "right", 4.2),
    ("absolutely", "nothing", 4.3), ("absolutely", "crucial", 4.2),
    ("absolutely", "brilliant", 4.1), ("absolutely", "clear", 4.2),
    ("thoroughly", "enjoyed", 4.3), ("thoroughly", "investigated", 4.2),
    ("thoroughly", "examined", 4.2), ("thoroughly", "tested", 4.1),
    ("thoroughly", "cleaned", 4.0), ("thoroughly", "prepared", 4.0),
    ("entirely", "different", 4.4), ("entirely", "new", 4.2),
    ("entirely", "possible", 4.1), ("entirely", "dependent", 4.0),
    ("entirely", "separate", 4.0), ("entirely", "clear", 3.9),
    ("completely", "different", 4.5), ("completely", "wrong", 4.3),
    ("completely", "destroyed", 4.3), ("completely", "new", 4.1),
    ("completely", "free", 4.1), ("completely", "changed", 4.1),
    ("completely", "ignored", 4.2), ("completely", "forgotten", 4.2),
    ("completely", "overwhelmed", 4.1), ("completely", "satisfied", 4.0),
    ("extremely", "important", 4.6), ("extremely", "difficult", 4.5),
    ("extremely", "dangerous", 4.4), ("extremely", "useful", 4.3),
    ("extremely", "rare", 4.4), ("extremely", "complex", 4.2),
    ("extremely", "popular", 4.3), ("extremely", "effective", 4.2),
    ("extremely", "pleased", 4.1), ("extremely", "unlikely", 4.3),
    ("remarkably", "similar", 4.3), ("remarkably", "well", 4.1),
    ("remarkably", "successful", 4.0), ("remarkably", "stable", 3.9),
    ("significantly", "higher", 4.5), ("significantly", "lower", 4.4),
    ("significantly", "different", 4.3), ("significantly", "reduced", 4.3),
    ("significantly", "increased", 4.3), ("significantly", "improved", 4.2),
    ("considerably", "more", 4.3), ("considerably", "less", 4.1),
    ("considerably", "higher", 4.2), ("considerably", "lower", 4.1),
    ("substantially", "more", 4.3), ("substantially", "less", 4.0),
    ("substantially", "higher", 4.1), ("substantially", "different", 4.0),
    ("relatively", "new", 4.2), ("relatively", "small", 4.2),
    ("relatively", "few", 4.1), ("relatively", "simple", 4.0),
    ("relatively", "low", 4.1), ("relatively", "high", 4.0),
    ("relatively", "easy", 3.9), ("relatively", "cheap", 3.9),
    ("increasingly", "important", 4.4), ("increasingly", "popular", 4.3),
    ("increasingly", "difficult", 4.3), ("increasingly", "common", 4.2),
    ("increasingly", "concerned", 4.2), ("increasingly", "clear", 4.1),
    ("increasingly", "complex", 4.1), ("increasingly", "evident", 4.1),
    ("undeniably", "important", 4.0), ("unquestionably", "right", 3.9),
    ("profoundly", "affected", 4.3), ("profoundly", "influenced", 4.2),
    ("profoundly", "changed", 4.1), ("profoundly", "different", 4.0),
    ("noticeably", "different", 4.0), ("noticeably", "absent", 3.9),
    ("markedly", "different", 4.2), ("markedly", "improved", 4.0),
    ("overwhelmingly", "positive", 4.1), ("overwhelmingly", "negative", 3.9),
    ("predominantly", "male", 4.0), ("predominantly", "female", 3.9),
    ("predominantly", "white", 3.9), ("predominantly", "urban", 3.8),
    ("disproportionately", "affected", 4.1),
    ("fundamentally", "different", 4.3), ("fundamentally", "flawed", 4.2),
    ("fundamentally", "changed", 4.1), ("fundamentally", "wrong", 4.0),
    ("inherently", "dangerous", 4.1), ("inherently", "risky", 3.9),
    ("inherently", "flawed", 4.0), ("inherently", "unfair", 3.9),
    ("fiercely", "competitive", 4.2), ("fiercely", "independent", 4.1),
    ("fiercely", "opposed", 4.0), ("fiercely", "contested", 4.0),
    ("ridiculously", "expensive", 4.0), ("ridiculously", "easy", 3.8),
    ("painfully", "slow", 4.1), ("painfully", "obvious", 4.0),
    ("painfully", "aware", 4.0), ("excruciatingly", "painful", 3.9),
    ("blissfully", "unaware", 4.2), ("blissfully", "ignorant", 4.0),
    ("woefully", "inadequate", 4.1), ("woefully", "unprepared", 4.0),
    ("blatantly", "obvious", 4.0), ("blatantly", "wrong", 3.9),
    ("patently", "absurd", 3.9), ("patently", "false", 4.0),
    ("categorically", "denied", 4.2), ("categorically", "rejected", 4.0),
    ("wholeheartedly", "agree", 4.0), ("wholeheartedly", "support", 3.9),
    ("desperately", "needed", 4.2), ("desperately", "wanted", 4.0),
    ("stubbornly", "refused", 4.0), ("flatly", "refused", 4.1),
    ("flatly", "denied", 4.0), ("vehemently", "denied", 4.1),
    ("vehemently", "opposed", 4.2), ("staunchly", "defended", 4.0),
    ("staunchly", "opposed", 3.9), ("emphatically", "denied", 4.0),
    ("cautiously", "optimistic", 4.3), ("guardedly", "optimistic", 4.0),
    
    # ── Adjective + Noun collocations ──
    ("significant", "impact", 4.9), ("significant", "role", 4.6),
    ("significant", "change", 4.5), ("significant", "difference", 4.6),
    ("significant", "improvement", 4.5), ("significant", "progress", 4.4),
    ("significant", "contribution", 4.4), ("significant", "amount", 4.5),
    ("significant", "portion", 4.3), ("significant", "reduction", 4.3),
    ("significant", "increase", 4.4), ("significant", "risk", 4.3),
    ("significant", "challenge", 4.2), ("significant", "achievement", 4.2),
    ("significant", "advantage", 4.2), ("significant", "effect", 4.3),
    ("crucial", "role", 4.8), ("crucial", "decision", 4.5),
    ("crucial", "factor", 4.6), ("crucial", "moment", 4.4),
    ("crucial", "importance", 4.4), ("crucial", "step", 4.3),
    ("crucial", "element", 4.3), ("crucial", "issue", 4.3),
    ("crucial", "aspect", 4.2), ("crucial", "point", 4.2),
    ("vital", "role", 4.6), ("vital", "importance", 4.4),
    ("vital", "information", 4.3), ("vital", "sign", 4.5),
    ("vital", "organ", 4.4), ("vital", "component", 4.2),
    ("vital", "resource", 4.1), ("vital", "interest", 4.2),
    ("key", "factor", 4.8), ("key", "role", 4.7),
    ("key", "issue", 4.5), ("key", "element", 4.5),
    ("key", "player", 4.4), ("key", "component", 4.4),
    ("key", "indicator", 4.4), ("key", "feature", 4.3),
    ("key", "objective", 4.2), ("key", "stakeholder", 4.3),
    ("key", "challenge", 4.2), ("key", "finding", 4.3),
    ("key", "principle", 4.2), ("key", "priority", 4.3),
    ("key", "concern", 4.1), ("key", "driver", 4.3),
    ("major", "role", 4.6), ("major", "impact", 4.5),
    ("major", "concern", 4.4), ("major", "challenge", 4.4),
    ("major", "issue", 4.4), ("major", "factor", 4.3),
    ("major", "problem", 4.4), ("major", "change", 4.3),
    ("major", "breakthrough", 4.5), ("major", "decision", 4.2),
    ("major", "achievement", 4.2), ("major", "contribution", 4.1),
    ("major", "advantage", 4.1), ("major", "obstacle", 4.2),
    ("major", "crisis", 4.3), ("major", "disaster", 4.3),
    ("profound", "impact", 4.7), ("profound", "effect", 4.5),
    ("profound", "influence", 4.5), ("profound", "change", 4.3),
    ("profound", "implications", 4.4), ("profound", "consequences", 4.3),
    ("profound", "understanding", 4.2), ("profound", "transformation", 4.1),
    ("sharp", "increase", 4.8), ("sharp", "decline", 4.7),
    ("sharp", "rise", 4.6), ("sharp", "drop", 4.5),
    ("sharp", "fall", 4.5), ("sharp", "contrast", 4.6),
    ("sharp", "criticism", 4.3), ("sharp", "pain", 4.2),
    ("steep", "rise", 4.5), ("steep", "decline", 4.4),
    ("steep", "drop", 4.3), ("steep", "increase", 4.3),
    ("steep", "hill", 4.1), ("steep", "slope", 4.2),
    ("dramatic", "increase", 4.6), ("dramatic", "change", 4.5),
    ("dramatic", "improvement", 4.4), ("dramatic", "effect", 4.3),
    ("dramatic", "rise", 4.3), ("dramatic", "shift", 4.3),
    ("dramatic", "reduction", 4.2), ("dramatic", "transformation", 4.2),
    ("swift", "action", 4.4), ("swift", "response", 4.3),
    ("swift", "decision", 4.1), ("swift", "justice", 4.0),
    ("bitter", "dispute", 4.3), ("bitter", "rivalry", 4.2),
    ("bitter", "disappointment", 4.3), ("bitter", "experience", 4.0),
    ("bitter", "enemy", 4.1), ("bitter", "truth", 4.0),
    ("fierce", "competition", 4.6), ("fierce", "opposition", 4.4),
    ("fierce", "debate", 4.3), ("fierce", "resistance", 4.3),
    ("fierce", "battle", 4.3), ("fierce", "fighting", 4.2),
    ("fierce", "criticism", 4.2), ("fierce", "loyalty", 4.0),
    ("stiff", "competition", 4.4), ("stiff", "resistance", 4.2),
    ("stiff", "penalty", 4.1), ("stiff", "opposition", 4.0),
    ("heated", "debate", 4.7), ("heated", "argument", 4.5),
    ("heated", "discussion", 4.4), ("heated", "exchange", 4.3),
    ("broad", "range", 4.8), ("broad", "spectrum", 4.5),
    ("broad", "scope", 4.3), ("broad", "consensus", 4.3),
    ("broad", "support", 4.2), ("broad", "overview", 4.1),
    ("wide", "range", 5.0), ("wide", "variety", 4.8),
    ("wide", "array", 4.5), ("wide", "margin", 4.3),
    ("wide", "gap", 4.2), ("wide", "selection", 4.2),
    ("vast", "majority", 5.1), ("vast", "amount", 4.5),
    ("vast", "number", 4.4), ("vast", "resources", 4.2),
    ("vast", "experience", 4.2), ("vast", "knowledge", 4.1),
    ("vast", "array", 4.3), ("vast", "network", 4.1),
    ("overwhelming", "majority", 4.9), ("overwhelming", "support", 4.5),
    ("overwhelming", "evidence", 4.6), ("overwhelming", "desire", 4.1),
    ("overwhelming", "response", 4.2), ("overwhelming", "force", 4.1),
    ("slim", "chance", 4.5), ("slim", "margin", 4.3),
    ("slim", "majority", 4.1), ("slim", "possibility", 4.0),
    ("golden", "opportunity", 4.4), ("golden", "age", 4.3),
    ("golden", "rule", 4.2), ("golden", "era", 4.1),
    ("prime", "minister", 5.2), ("prime", "example", 4.3),
    ("prime", "candidate", 4.1), ("prime", "target", 4.1),
    ("public", "opinion", 4.9), ("public", "interest", 4.7),
    ("public", "health", 4.8), ("public", "sector", 4.7),
    ("public", "service", 4.6), ("public", "awareness", 4.5),
    ("public", "debate", 4.4), ("public", "scrutiny", 4.3),
    ("public", "confidence", 4.3), ("public", "spending", 4.4),
    ("public", "transport", 4.5), ("public", "safety", 4.4),
    ("common", "sense", 4.8), ("common", "ground", 4.5),
    ("common", "practice", 4.4), ("common", "knowledge", 4.3),
    ("common", "misconception", 4.3), ("common", "theme", 4.1),
    ("common", "goal", 4.1), ("common", "cause", 4.2),
    ("grave", "concern", 4.5), ("grave", "mistake", 4.4),
    ("grave", "danger", 4.3), ("grave", "consequences", 4.3),
    ("grave", "error", 4.2), ("grave", "risk", 4.1),
    ("grave", "threat", 4.2), ("grave", "situation", 4.0),
    ("fatal", "error", 4.5), ("fatal", "flaw", 4.4),
    ("fatal", "accident", 4.3), ("fatal", "mistake", 4.3),
    ("fatal", "blow", 4.2), ("fatal", "consequence", 4.1),
    ("vicious", "cycle", 4.6), ("vicious", "circle", 4.5),
    ("vicious", "attack", 4.3), ("vicious", "campaign", 4.0),
    ("chronic", "illness", 4.4), ("chronic", "disease", 4.4),
    ("chronic", "pain", 4.4), ("chronic", "problem", 4.2),
    ("chronic", "shortage", 4.1), ("chronic", "condition", 4.3),
    ("acute", "pain", 4.3), ("acute", "shortage", 4.2),
    ("acute", "problem", 4.1), ("acute", "crisis", 4.1),
    ("acute", "awareness", 4.0), ("acute", "need", 4.0),
    ("utter", "chaos", 4.3), ("utter", "nonsense", 4.2),
    ("utter", "devastation", 4.1), ("utter", "disbelief", 4.1),
    ("utter", "failure", 4.0), ("sheer", "number", 4.2),
    ("sheer", "volume", 4.2), ("sheer", "scale", 4.3),
    ("sheer", "size", 4.1), ("sheer", "force", 4.1),
    ("sheer", "determination", 4.1), ("sheer", "luck", 4.0),
    ("mere", "fact", 4.2), ("mere", "mention", 4.1),
    ("mere", "thought", 4.0), ("mere", "fraction", 4.0),
    ("stark", "contrast", 4.5), ("stark", "reminder", 4.2),
    ("stark", "reality", 4.1), ("stark", "warning", 4.0),
    ("stark", "difference", 4.1), ("striking", "resemblance", 4.4),
    ("striking", "contrast", 4.2), ("striking", "feature", 4.0),
    ("striking", "example", 4.0), ("stunning", "victory", 4.2),
    ("stunning", "defeat", 4.1), ("stunning", "revelation", 4.0),
    ("resounding", "success", 4.3), ("resounding", "victory", 4.2),
    ("resounding", "defeat", 4.0), ("sweeping", "changes", 4.3),
    ("sweeping", "reforms", 4.2), ("sweeping", "victory", 4.1),
    ("sweeping", "generalization", 4.0), ("mounting", "pressure", 4.4),
    ("mounting", "evidence", 4.3), ("mounting", "concern", 4.2),
    ("mounting", "debt", 4.1), ("mounting", "tension", 4.2),
    ("growing", "concern", 4.4), ("growing", "demand", 4.3),
    ("growing", "number", 4.3), ("growing", "trend", 4.2),
    ("growing", "awareness", 4.2), ("growing", "evidence", 4.2),
    ("growing", "pressure", 4.2), ("growing", "tension", 4.1),
    ("growing", "frustration", 4.1), ("growing", "influence", 4.0),
    ("daunting", "task", 4.3), ("daunting", "challenge", 4.2),
    ("daunting", "prospect", 4.1), ("formidable", "challenge", 4.2),
    ("formidable", "opponent", 4.2), ("formidable", "task", 4.1),
    ("insurmountable", "obstacle", 4.1), ("insurmountable", "challenge", 3.9),
    ("overwhelming", "odds", 4.1), ("considerable", "amount", 4.3),
    ("considerable", "effort", 4.3), ("considerable", "attention", 4.1),
    ("considerable", "influence", 4.1), ("considerable", "experience", 4.0),
    ("considerable", "interest", 4.0), ("considerable", "progress", 4.1),
    ("enormous", "amount", 4.3), ("enormous", "pressure", 4.2),
    ("enormous", "potential", 4.1), ("enormous", "impact", 4.1),
    ("enormous", "challenge", 4.0), ("enormous", "effort", 4.0),
    ("tremendous", "amount", 4.2), ("tremendous", "pressure", 4.2),
    ("tremendous", "impact", 4.1), ("tremendous", "opportunity", 4.0),
    ("tremendous", "success", 4.1), ("tremendous", "potential", 4.0),
    ("immense", "pressure", 4.2), ("immense", "importance", 4.1),
    ("paramount", "importance", 4.4), ("paramount", "concern", 4.1),
    ("pivotal", "role", 4.4), ("pivotal", "moment", 4.2),
    ("pivotal", "decision", 4.0), ("instrumental", "role", 4.3),
    ("integral", "part", 4.5), ("integral", "role", 4.2),
    ("integral", "component", 4.1), ("indispensable", "role", 4.0),
    ("underlying", "cause", 4.4), ("underlying", "problem", 4.3),
    ("underlying", "issue", 4.2), ("underlying", "principle", 4.2),
    ("underlying", "mechanism", 4.2), ("underlying", "assumption", 4.1),
    ("overarching", "goal", 4.1), ("overarching", "theme", 4.0),
    ("overarching", "objective", 3.9), ("overarching", "strategy", 3.9),
    ("compelling", "evidence", 4.4), ("compelling", "argument", 4.3),
    ("compelling", "reason", 4.2), ("compelling", "case", 4.1),
    ("compelling", "story", 4.0), ("convincing", "argument", 4.2),
    ("convincing", "evidence", 4.2), ("convincing", "case", 4.0),
    ("concrete", "evidence", 4.2), ("concrete", "example", 4.3),
    ("concrete", "step", 4.1), ("concrete", "plan", 4.1),
    ("concrete", "action", 4.0), ("concrete", "measure", 4.0),
    ("tangible", "result", 4.2), ("tangible", "benefit", 4.1),
    ("tangible", "evidence", 4.0), ("tangible", "progress", 4.0),
    ("definitive", "answer", 4.1), ("definitive", "guide", 4.0),
    ("definitive", "proof", 4.1), ("definitive", "conclusion", 4.0),
    
    # ── Verb + Noun collocations ──
    ("make", "decision", 4.8), ("make", "progress", 4.7),
    ("make", "mistake", 4.6), ("make", "effort", 4.5),
    ("make", "choice", 4.4), ("make", "contribution", 4.4),
    ("make", "difference", 4.5), ("make", "improvement", 4.2),
    ("make", "commitment", 4.3), ("make", "comparison", 4.1),
    ("make", "concession", 4.1), ("make", "prediction", 4.1),
    ("make", "recommendation", 4.2), ("make", "adjustment", 4.1),
    ("make", "arrangement", 4.2), ("make", "assumption", 4.2),
    ("make", "attempt", 4.1), ("make", "connection", 4.1),
    ("make", "discovery", 4.0), ("make", "distinction", 4.1),
    ("make", "exception", 4.1), ("make", "impression", 4.2),
    ("make", "observation", 4.0), ("make", "profit", 4.1),
    ("make", "proposal", 4.0), ("make", "sacrifice", 4.0),
    ("make", "statement", 4.1), ("make", "transition", 4.0),
    ("take", "action", 4.9), ("take", "place", 5.0),
    ("take", "advantage", 4.7), ("take", "responsibility", 4.6),
    ("take", "measure", 4.5), ("take", "step", 4.5),
    ("take", "approach", 4.3), ("take", "risk", 4.4),
    ("take", "initiative", 4.4), ("take", "opportunity", 4.2),
    ("take", "precedence", 4.2), ("take", "note", 4.2),
    ("take", "toll", 4.3), ("take", "account", 4.2),
    ("take", "care", 4.3), ("take", "effect", 4.2),
    ("take", "turn", 4.0), ("take", "stance", 4.1),
    ("take", "shape", 4.0), ("take", "pride", 4.1),
    ("pay", "attention", 5.0), ("pay", "tribute", 4.4),
    ("pay", "price", 4.3), ("pay", "respect", 4.2),
    ("pay", "dividend", 4.1), ("pay", "visit", 4.0),
    ("pay", "heed", 4.1), ("pay", "homage", 4.0),
    ("reach", "agreement", 4.6), ("reach", "conclusion", 4.5),
    ("reach", "consensus", 4.5), ("reach", "peak", 4.3),
    ("reach", "potential", 4.2), ("reach", "goal", 4.2),
    ("reach", "decision", 4.2), ("reach", "compromise", 4.3),
    ("reach", "milestone", 4.1), ("reach", "target", 4.2),
    ("draw", "conclusion", 4.6), ("draw", "attention", 4.7),
    ("draw", "comparison", 4.3), ("draw", "distinction", 4.3),
    ("draw", "parallel", 4.2), ("draw", "criticism", 4.2),
    ("draw", "inspiration", 4.1), ("draw", "line", 4.0),
    ("raise", "awareness", 4.7), ("raise", "concern", 4.5),
    ("raise", "question", 4.5), ("raise", "issue", 4.4),
    ("raise", "fund", 4.3), ("raise", "standard", 4.2),
    ("raise", "profile", 4.1), ("raise", "alarm", 4.2),
    ("raise", "doubt", 4.1), ("raise", "bar", 4.1),
    ("raise", "objection", 4.0), ("raise", "expectation", 4.1),
    ("pose", "threat", 4.6), ("pose", "challenge", 4.5),
    ("pose", "risk", 4.4), ("pose", "danger", 4.3),
    ("pose", "question", 4.2), ("pose", "problem", 4.2),
    ("pose", "difficulty", 4.0), ("pose", "dilemma", 4.0),
    ("face", "challenge", 4.6), ("face", "problem", 4.5),
    ("face", "difficulty", 4.4), ("face", "obstacle", 4.3),
    ("face", "criticism", 4.3), ("face", "opposition", 4.3),
    ("face", "consequence", 4.3), ("face", "reality", 4.1),
    ("face", "prospect", 4.1), ("face", "pressure", 4.2),
    ("face", "risk", 4.2), ("face", "threat", 4.2),
    ("meet", "demand", 4.5), ("meet", "requirement", 4.4),
    ("meet", "need", 4.4), ("meet", "expectation", 4.3),
    ("meet", "criterion", 4.2), ("meet", "standard", 4.3),
    ("meet", "challenge", 4.2), ("meet", "deadline", 4.3),
    ("meet", "obligation", 4.1), ("meet", "target", 4.2),
    ("break", "record", 4.5), ("break", "silence", 4.4),
    ("break", "barrier", 4.3), ("break", "news", 4.4),
    ("break", "law", 4.2), ("break", "cycle", 4.1),
    ("break", "deadlock", 4.2), ("break", "ground", 4.1),
    ("break", "promise", 4.1), ("break", "rule", 4.0),
    ("set", "goal", 4.4), ("set", "standard", 4.5),
    ("set", "precedent", 4.4), ("set", "target", 4.3),
    ("set", "example", 4.2), ("set", "limit", 4.1),
    ("set", "tone", 4.2), ("set", "agenda", 4.1),
    ("set", "scene", 4.1), ("set", "stage", 4.2),
    ("set", "trend", 4.1), ("set", "record", 4.0),
    ("achieve", "goal", 4.5), ("achieve", "success", 4.4),
    ("achieve", "objective", 4.3), ("achieve", "result", 4.3),
    ("achieve", "target", 4.2), ("achieve", "balance", 4.1),
    ("achieve", "purpose", 4.0), ("achieve", "dream", 4.0),
    ("gain", "momentum", 4.5), ("gain", "experience", 4.4),
    ("gain", "access", 4.4), ("gain", "insight", 4.3),
    ("gain", "knowledge", 4.2), ("gain", "support", 4.2),
    ("gain", "confidence", 4.2), ("gain", "recognition", 4.1),
    ("gain", "advantage", 4.2), ("gain", "popularity", 4.1),
    ("gain", "ground", 4.1), ("gain", "understanding", 4.1),
    ("bear", "mind", 4.5), ("bear", "responsibility", 4.2),
    ("bear", "witness", 4.1), ("bear", "fruit", 4.1),
    ("bear", "resemblance", 4.2), ("bear", "brunt", 4.1),
    ("keep", "mind", 4.6), ("keep", "pace", 4.4),
    ("keep", "track", 4.3), ("keep", "promise", 4.2),
    ("keep", "record", 4.1), ("keep", "secret", 4.1),
    ("keep", "eye", 4.0), ("keep", "control", 4.0),
    ("run", "risk", 4.4), ("run", "business", 4.3),
    ("run", "campaign", 4.2), ("run", "operation", 4.1),
    ("run", "course", 4.0), ("run", "gamut", 4.0),
    ("commit", "crime", 4.5), ("commit", "offense", 4.3),
    ("commit", "murder", 4.4), ("commit", "fraud", 4.2),
    ("commit", "suicide", 4.4), ("commit", "resources", 4.0),
    ("launch", "campaign", 4.4), ("launch", "attack", 4.3),
    ("launch", "investigation", 4.2), ("launch", "initiative", 4.1),
    ("launch", "product", 4.2), ("launch", "appeal", 4.0),
    ("conduct", "research", 4.6), ("conduct", "investigation", 4.5),
    ("conduct", "survey", 4.4), ("conduct", "experiment", 4.3),
    ("conduct", "study", 4.3), ("conduct", "interview", 4.2),
    ("conduct", "review", 4.2), ("conduct", "audit", 4.1),
    ("perform", "task", 4.3), ("perform", "function", 4.2),
    ("perform", "duty", 4.2), ("perform", "analysis", 4.1),
    ("perform", "role", 4.0), ("perform", "operation", 4.1),
    ("carry", "out", 4.8), ("carry", "weight", 4.2),
    ("carry", "risk", 4.1), ("carry", "implication", 4.0),
    ("hold", "position", 4.2), ("hold", "view", 4.1),
    ("hold", "meeting", 4.2), ("hold", "election", 4.2),
    ("hold", "belief", 4.0), ("hold", "key", 4.1),
    ("hold", "promise", 4.0), ("hold", "record", 4.1),
    ("address", "issue", 4.5), ("address", "concern", 4.4),
    ("address", "problem", 4.4), ("address", "need", 4.3),
    ("address", "challenge", 4.2), ("address", "question", 4.1),
    ("tackle", "problem", 4.4), ("tackle", "issue", 4.3),
    ("tackle", "challenge", 4.3), ("tackle", "crisis", 4.1),
    ("tackle", "poverty", 4.0), ("tackle", "inequality", 3.9),
    ("overcome", "obstacle", 4.4), ("overcome", "challenge", 4.3),
    ("overcome", "difficulty", 4.3), ("overcome", "barrier", 4.2),
    ("overcome", "adversity", 4.1), ("overcome", "resistance", 4.1),
    ("exert", "pressure", 4.3), ("exert", "influence", 4.4),
    ("exert", "control", 4.1), ("exert", "force", 4.0),
    ("yield", "result", 4.1), ("yield", "profit", 4.0),
    ("yield", "benefit", 3.9), ("yield", "return", 4.0),
    ("impose", "restriction", 4.3), ("impose", "sanction", 4.3),
    ("impose", "ban", 4.2), ("impose", "fine", 4.1),
    ("impose", "limit", 4.1), ("impose", "penalty", 4.1),
    ("implement", "policy", 4.4), ("implement", "strategy", 4.3),
    ("implement", "plan", 4.3), ("implement", "reform", 4.2),
    ("implement", "measure", 4.2), ("implement", "change", 4.1),
    ("implement", "program", 4.1), ("implement", "solution", 4.1),
    ("establish", "framework", 4.3), ("establish", "relationship", 4.3),
    ("establish", "connection", 4.1), ("establish", "standard", 4.2),
    ("establish", "precedent", 4.2), ("establish", "identity", 4.0),
    ("foster", "growth", 4.2), ("foster", "development", 4.2),
    ("foster", "innovation", 4.1), ("foster", "cooperation", 4.1),
    ("foster", "environment", 4.0), ("foster", "relationship", 4.0),
    ("bridge", "gap", 4.4), ("bridge", "divide", 4.1),
    ("narrow", "gap", 4.2), ("narrow", "focus", 4.0),
    ("widen", "gap", 4.1), ("close", "gap", 4.2),
    ("fill", "gap", 4.2), ("fill", "void", 4.1),
    ("fill", "role", 4.0), ("fill", "position", 4.0),
    ("seize", "opportunity", 4.3), ("seize", "moment", 4.1),
    ("seize", "initiative", 4.0), ("seize", "power", 4.1),
    ("grasp", "concept", 4.1), ("grasp", "opportunity", 4.1),
    ("grasp", "significance", 4.0), ("embrace", "change", 4.2),
    ("embrace", "technology", 4.0), ("embrace", "opportunity", 4.0),
    ("shed", "light", 4.4), ("throw", "light", 4.1),
    ("cast", "doubt", 4.3), ("cast", "shadow", 4.1),
    ("cast", "vote", 4.1), ("cast", "light", 4.0),
    ("spark", "debate", 4.2), ("spark", "controversy", 4.1),
    ("spark", "interest", 4.0), ("spark", "outrage", 4.0),
    ("trigger", "response", 4.1), ("trigger", "reaction", 4.1),
    ("trigger", "crisis", 4.0), ("trigger", "alarm", 3.9),
    ("fuel", "speculation", 4.1), ("fuel", "debate", 4.0),
    ("fuel", "growth", 4.0), ("fuel", "concern", 3.9),
    ("stem", "tide", 4.0), ("stem", "flow", 3.9),
    ("curb", "inflation", 4.1), ("curb", "spending", 4.0),
    ("curb", "emission", 3.9), ("curb", "violence", 3.9),
    ("bolster", "support", 4.1), ("bolster", "confidence", 4.0),
    ("bolster", "security", 3.9), ("undermine", "confidence", 4.2),
    ("undermine", "authority", 4.1), ("undermine", "effort", 4.0),
    ("undermine", "credibility", 4.1), ("erode", "confidence", 4.1),
    ("erode", "trust", 4.1), ("erode", "support", 3.9),
    ("restore", "confidence", 4.2), ("restore", "order", 4.1),
    ("restore", "trust", 4.1), ("restore", "stability", 4.0),
    ("rebuild", "trust", 4.1), ("rebuild", "confidence", 4.0),
    
    # ── Preposition patterns ──
    ("interested", "in", 4.8), ("depend", "on", 4.9),
    ("rely", "on", 4.8), ("result", "in", 4.7),
    ("consist", "of", 4.8), ("apply", "to", 4.5),
    ("refer", "to", 4.7), ("belong", "to", 4.5),
    ("contribute", "to", 4.6), ("lead", "to", 4.7),
    ("due", "to", 4.9), ("according", "to", 5.0),
    ("thanks", "to", 4.5), ("prior", "to", 4.4),
    ("subject", "to", 4.5), ("prone", "to", 4.2),
    ("susceptible", "to", 4.2), ("immune", "to", 4.1),
    ("accused", "of", 4.5), ("aware", "of", 4.6),
    ("capable", "of", 4.5), ("guilty", "of", 4.4),
    ("fond", "of", 4.2), ("afraid", "of", 4.3),
    ("regardless", "of", 4.5), ("irrespective", "of", 4.2),
    ("devoid", "of", 4.1), ("indicative", "of", 4.2),
    ("reminiscent", "of", 4.2), ("symptomatic", "of", 4.0),
    ("compatible", "with", 4.3), ("consistent", "with", 4.5),
    ("associated", "with", 4.7), ("concerned", "with", 4.3),
    ("familiar", "with", 4.4), ("satisfied", "with", 4.3),
    ("pleased", "with", 4.1), ("equipped", "with", 4.2),
    ("faced", "with", 4.3), ("confronted", "with", 4.2),
    ("blessed", "with", 4.0), ("burdened", "with", 4.0),
    ("responsible", "for", 4.7), ("famous", "for", 4.4),
    ("known", "for", 4.5), ("renowned", "for", 4.4),
    ("notorious", "for", 4.3), ("designed", "for", 4.3),
    ("intended", "for", 4.2), ("suitable", "for", 4.3),
    ("eligible", "for", 4.2), ("essential", "for", 4.3),
    ("crucial", "for", 4.2), ("vital", "for", 4.1),
    ("necessary", "for", 4.3), ("sufficient", "for", 4.1),
    ("harmful", "to", 4.2), ("beneficial", "to", 4.2),
    ("detrimental", "to", 4.3), ("conducive", "to", 4.1),
    ("relevant", "to", 4.3), ("pertinent", "to", 4.1),
    ("contrary", "to", 4.3), ("opposed", "to", 4.2),
    ("committed", "to", 4.4), ("dedicated", "to", 4.3),
    ("devoted", "to", 4.2), ("exposed", "to", 4.3),
    ("subjected", "to", 4.2), ("confined", "to", 4.1),
    ("limited", "to", 4.2), ("restricted", "to", 4.1),
    ("entitled", "to", 4.2), ("accustomed", "to", 4.1),
    ("attributed", "to", 4.3), ("equivalent", "to", 4.1),
    ("superior", "to", 4.2), ("inferior", "to", 4.1),
    ("analogous", "to", 4.0), ("adjacent", "to", 4.0),
    ("pursuant", "to", 4.1), ("integral", "to", 4.1),
    ("central", "to", 4.2), ("crucial", "to", 4.2),
    ("conducive", "to", 4.1), ("amenable", "to", 4.0),
    ("averse", "to", 4.0), ("oblivious", "to", 4.1),
    ("impervious", "to", 4.0), ("immune", "to", 4.1),
    ("akin", "to", 4.0), ("tantamount", "to", 4.1),
    ("derived", "from", 4.2), ("different", "from", 4.4),
    ("distinct", "from", 4.2), ("stemming", "from", 4.0),
    ("arising", "from", 4.1), ("resulting", "from", 4.2),
    ("benefiting", "from", 4.0), ("suffering", "from", 4.2),
    ("ranging", "from", 4.1), ("absent", "from", 4.0),
    ("inseparable", "from", 4.0), ("dependent", "on", 4.4),
    ("contingent", "on", 4.1), ("incumbent", "on", 4.0),
    ("predicated", "on", 4.0), ("based", "on", 4.7),
    ("focused", "on", 4.4), ("centered", "on", 4.2),
    ("concentrated", "on", 4.1), ("intent", "on", 4.0),
    ("keen", "on", 4.0), ("embarked", "on", 4.0),
    ("engaged", "in", 4.4), ("involved", "in", 4.5),
    ("resulted", "in", 4.5), ("succeeded", "in", 4.2),
    ("participated", "in", 4.2), ("specialized", "in", 4.2),
    ("invested", "in", 4.3), ("immersed", "in", 4.0),
    ("steeped", "in", 4.0), ("rooted", "in", 4.2),
    ("grounded", "in", 4.1), ("embedded", "in", 4.2),
    ("enshrined", "in", 4.0), ("anchored", "in", 4.0),
    
    # ── Business / Economy ──
    ("economic", "growth", 4.8), ("economic", "development", 4.7),
    ("economic", "recovery", 4.5), ("economic", "downturn", 4.5),
    ("economic", "crisis", 4.5), ("economic", "policy", 4.4),
    ("economic", "impact", 4.4), ("economic", "reform", 4.3),
    ("economic", "stability", 4.3), ("economic", "prosperity", 4.2),
    ("economic", "activity", 4.3), ("economic", "performance", 4.2),
    ("economic", "inequality", 4.2), ("economic", "benefit", 4.1),
    ("financial", "crisis", 4.7), ("financial", "support", 4.5),
    ("financial", "institution", 4.6), ("financial", "market", 4.6),
    ("financial", "stability", 4.4), ("financial", "resource", 4.3),
    ("financial", "difficulty", 4.2), ("financial", "performance", 4.2),
    ("financial", "burden", 4.2), ("financial", "incentive", 4.1),
    ("fiscal", "policy", 4.5), ("fiscal", "year", 4.6),
    ("fiscal", "deficit", 4.3), ("fiscal", "responsibility", 4.2),
    ("fiscal", "stimulus", 4.2), ("monetary", "policy", 4.6),
    ("monetary", "system", 4.2), ("monetary", "value", 4.1),
    ("budget", "deficit", 4.5), ("budget", "surplus", 4.3),
    ("budget", "constraint", 4.2), ("budget", "allocation", 4.1),
    ("trade", "deficit", 4.4), ("trade", "surplus", 4.3),
    ("trade", "agreement", 4.4), ("trade", "barrier", 4.3),
    ("trade", "policy", 4.2), ("trade", "relation", 4.2),
    ("market", "share", 4.6), ("market", "value", 4.5),
    ("market", "force", 4.3), ("market", "condition", 4.3),
    ("market", "economy", 4.4), ("market", "demand", 4.3),
    ("market", "trend", 4.2), ("market", "competition", 4.2),
    ("stock", "market", 4.7), ("stock", "price", 4.4),
    ("stock", "exchange", 4.5), ("stock", "option", 4.2),
    ("interest", "rate", 4.8), ("interest", "group", 4.3),
    ("exchange", "rate", 4.6), ("inflation", "rate", 4.5),
    ("unemployment", "rate", 4.6), ("growth", "rate", 4.5),
    ("profit", "margin", 4.5), ("net", "profit", 4.4),
    ("gross", "profit", 4.3), ("operating", "profit", 4.2),
    ("revenue", "stream", 4.2), ("revenue", "growth", 4.2),
    ("corporate", "governance", 4.4), ("corporate", "social", 4.2),
    ("corporate", "culture", 4.2), ("corporate", "responsibility", 4.3),
    ("corporate", "strategy", 4.2), ("competitive", "advantage", 4.5),
    ("competitive", "edge", 4.3), ("competitive", "market", 4.3),
    ("competitive", "landscape", 4.1), ("sustainable", "development", 4.5),
    ("sustainable", "growth", 4.3), ("sustainable", "energy", 4.2),
    ("renewable", "energy", 4.6), ("renewable", "resource", 4.3),
    ("supply", "chain", 4.7), ("supply", "demand", 4.4),
    ("value", "chain", 4.3), ("value", "proposition", 4.2),
    
    # ── Academic / Research ──
    ("empirical", "evidence", 4.6), ("empirical", "research", 4.5),
    ("empirical", "data", 4.4), ("empirical", "study", 4.3),
    ("empirical", "finding", 4.2), ("theoretical", "framework", 4.5),
    ("theoretical", "approach", 4.3), ("theoretical", "perspective", 4.2),
    ("theoretical", "foundation", 4.2), ("theoretical", "basis", 4.1),
    ("systematic", "review", 4.5), ("systematic", "approach", 4.4),
    ("systematic", "analysis", 4.3), ("systematic", "study", 4.2),
    ("comprehensive", "review", 4.4), ("comprehensive", "analysis", 4.4),
    ("comprehensive", "study", 4.3), ("comprehensive", "approach", 4.2),
    ("comprehensive", "assessment", 4.2), ("comprehensive", "plan", 4.1),
    ("comprehensive", "strategy", 4.1), ("comprehensive", "framework", 4.1),
    ("preliminary", "result", 4.3), ("preliminary", "finding", 4.2),
    ("preliminary", "analysis", 4.2), ("preliminary", "study", 4.1),
    ("preliminary", "investigation", 4.1), ("preliminary", "assessment", 4.0),
    ("qualitative", "research", 4.4), ("qualitative", "data", 4.3),
    ("qualitative", "analysis", 4.3), ("qualitative", "study", 4.1),
    ("quantitative", "research", 4.4), ("quantitative", "data", 4.4),
    ("quantitative", "analysis", 4.3), ("quantitative", "method", 4.2),
    ("rigorous", "analysis", 4.3), ("rigorous", "standard", 4.1),
    ("rigorous", "testing", 4.1), ("rigorous", "approach", 4.0),
    ("robust", "evidence", 4.2), ("robust", "framework", 4.1),
    ("robust", "system", 4.0), ("robust", "method", 4.0),
    ("peer", "review", 4.5), ("peer", "pressure", 4.3),
    ("statistical", "analysis", 4.5), ("statistical", "significance", 4.5),
    ("statistical", "method", 4.3), ("statistical", "data", 4.2),
    ("statistical", "model", 4.2), ("statistical", "evidence", 4.1),
    ("causal", "relationship", 4.3), ("causal", "link", 4.2),
    ("causal", "connection", 4.0), ("causal", "factor", 4.0),
    ("correlation", "between", 4.2), ("correlation", "coefficient", 4.3),
    ("hypothesis", "testing", 4.3), ("null", "hypothesis", 4.4),
    ("sample", "size", 4.4), ("sample", "population", 4.1),
    ("control", "group", 4.4), ("experimental", "group", 4.2),
    ("longitudinal", "study", 4.3), ("cross", "sectional", 4.2),
    ("case", "study", 4.5), ("field", "study", 4.1),
    ("literature", "review", 4.5), ("body", "literature", 4.2),
    ("body", "evidence", 4.3), ("body", "knowledge", 4.2),
    ("body", "work", 4.1), ("seminal", "work", 4.2),
    ("groundbreaking", "research", 4.3), ("groundbreaking", "discovery", 4.2),
    ("cutting", "edge", 4.4), ("state", "art", 4.5),
    
    # ── Legal / Government ──
    ("legal", "framework", 4.4), ("legal", "system", 4.3),
    ("legal", "action", 4.3), ("legal", "obligation", 4.2),
    ("legal", "requirement", 4.3), ("legal", "right", 4.3),
    ("legal", "proceedings", 4.2), ("legal", "counsel", 4.2),
    ("legal", "basis", 4.2), ("legal", "dispute", 4.1),
    ("constitutional", "right", 4.4), ("constitutional", "amendment", 4.3),
    ("constitutional", "court", 4.2), ("constitutional", "reform", 4.1),
    ("legislative", "body", 4.1), ("legislative", "process", 4.2),
    ("legislative", "framework", 4.1), ("legislative", "reform", 4.0),
    ("judicial", "system", 4.3), ("judicial", "review", 4.3),
    ("judicial", "proceedings", 4.1), ("judicial", "decision", 4.1),
    ("regulatory", "framework", 4.3), ("regulatory", "body", 4.2),
    ("regulatory", "requirement", 4.2), ("regulatory", "compliance", 4.2),
    ("political", "party", 4.5), ("political", "system", 4.4),
    ("political", "power", 4.4), ("political", "leadership", 4.2),
    ("political", "stability", 4.3), ("political", "reform", 4.2),
    ("political", "crisis", 4.3), ("political", "influence", 4.2),
    ("political", "agenda", 4.1), ("political", "landscape", 4.1),
    ("democratic", "system", 4.2), ("democratic", "process", 4.2),
    ("democratic", "institution", 4.2), ("democratic", "society", 4.1),
    ("democratic", "governance", 4.1), ("democratic", "election", 4.2),
    ("civil", "society", 4.4), ("civil", "liberty", 4.3),
    ("civil", "right", 4.4), ("civil", "war", 4.5),
    ("civil", "servant", 4.2), ("civil", "unrest", 4.1),
    ("human", "right", 4.8), ("human", "resource", 4.5),
    ("human", "capital", 4.3), ("human", "nature", 4.3),
    ("human", "being", 4.4), ("human", "development", 4.3),
    ("foreign", "policy", 4.6), ("foreign", "affairs", 4.5),
    ("foreign", "investment", 4.4), ("foreign", "minister", 4.3),
    ("domestic", "policy", 4.3), ("domestic", "market", 4.2),
    ("domestic", "violence", 4.3), ("domestic", "affairs", 4.1),
    
    # ── Health / Medicine ──
    ("mental", "health", 4.8), ("mental", "illness", 4.6),
    ("mental", "disorder", 4.4), ("mental", "wellbeing", 4.3),
    ("mental", "capacity", 4.1), ("physical", "health", 4.5),
    ("physical", "activity", 4.5), ("physical", "exercise", 4.3),
    ("physical", "disability", 4.2), ("physical", "fitness", 4.2),
    ("clinical", "trial", 4.7), ("clinical", "study", 4.4),
    ("clinical", "practice", 4.4), ("clinical", "evidence", 4.2),
    ("clinical", "outcome", 4.2), ("clinical", "setting", 4.1),
    ("adverse", "effect", 4.5), ("adverse", "reaction", 4.3),
    ("adverse", "impact", 4.2), ("adverse", "consequence", 4.1),
    ("adverse", "condition", 4.0), ("side", "effect", 4.6),
    ("life", "expectancy", 4.5), ("life", "span", 4.2),
    ("life", "quality", 4.1), ("mortality", "rate", 4.5),
    ("survival", "rate", 4.4), ("infection", "rate", 4.2),
    ("immune", "system", 4.5), ("immune", "response", 4.3),
    ("blood", "pressure", 4.7), ("blood", "sugar", 4.4),
    ("blood", "vessel", 4.3), ("blood", "flow", 4.2),
    ("heart", "disease", 4.6), ("heart", "attack", 4.6),
    ("heart", "failure", 4.4), ("heart", "rate", 4.4),
    ("risk", "factor", 4.6), ("risk", "assessment", 4.4),
    ("risk", "management", 4.4), ("risk", "reduction", 4.2),
    ("dose", "response", 4.1), ("drug", "interaction", 4.1),
    
    # ── Technology ──
    ("artificial", "intelligence", 4.9), ("machine", "learning", 4.8),
    ("deep", "learning", 4.6), ("neural", "network", 4.7),
    ("natural", "language", 4.5), ("big", "data", 4.6),
    ("data", "analysis", 4.5), ("data", "collection", 4.4),
    ("data", "processing", 4.3), ("data", "mining", 4.3),
    ("data", "set", 4.3), ("data", "driven", 4.3),
    ("data", "security", 4.2), ("data", "protection", 4.3),
    ("data", "privacy", 4.2), ("data", "breach", 4.3),
    ("digital", "transformation", 4.4), ("digital", "technology", 4.3),
    ("digital", "platform", 4.2), ("digital", "economy", 4.2),
    ("digital", "literacy", 4.1), ("digital", "divide", 4.1),
    ("cyber", "security", 4.5), ("cyber", "attack", 4.4),
    ("cyber", "threat", 4.2), ("cyber", "crime", 4.2),
    ("cloud", "computing", 4.5), ("cloud", "service", 4.2),
    ("cloud", "storage", 4.2), ("cloud", "platform", 4.1),
    ("open", "source", 4.5), ("source", "code", 4.4),
    ("user", "interface", 4.4), ("user", "experience", 4.4),
    ("user", "friendly", 4.2), ("user", "data", 4.2),
    ("software", "development", 4.4), ("software", "engineering", 4.3),
    ("software", "system", 4.1), ("software", "application", 4.1),
    ("operating", "system", 4.6), ("information", "technology", 4.5),
    ("information", "system", 4.4), ("information", "security", 4.3),
    
    # ── Education ──
    ("higher", "education", 4.7), ("primary", "education", 4.4),
    ("secondary", "education", 4.3), ("vocational", "training", 4.3),
    ("professional", "development", 4.4), ("academic", "performance", 4.3),
    ("academic", "achievement", 4.3), ("academic", "research", 4.3),
    ("academic", "institution", 4.3), ("academic", "standard", 4.1),
    ("learning", "outcome", 4.3), ("learning", "process", 4.2),
    ("learning", "environment", 4.2), ("learning", "experience", 4.1),
    ("critical", "thinking", 4.6), ("critical", "analysis", 4.4),
    ("critical", "role", 4.4), ("critical", "factor", 4.2),
    ("critical", "issue", 4.2), ("critical", "importance", 4.2),
    ("problem", "solving", 4.5), ("decision", "making", 4.6),
    ("policy", "making", 4.4), ("sense", "making", 4.0),
    
    # ── Environment ──
    ("climate", "change", 4.9), ("global", "warming", 4.8),
    ("greenhouse", "gas", 4.7), ("carbon", "emission", 4.6),
    ("carbon", "footprint", 4.4), ("carbon", "dioxide", 4.5),
    ("fossil", "fuel", 4.7), ("natural", "resource", 4.5),
    ("natural", "disaster", 4.4), ("natural", "environment", 4.3),
    ("natural", "habitat", 4.3), ("natural", "phenomenon", 4.1),
    ("environmental", "impact", 4.5), ("environmental", "protection", 4.4),
    ("environmental", "policy", 4.3), ("environmental", "damage", 4.3),
    ("environmental", "sustainability", 4.3), ("environmental", "issue", 4.2),
    ("ecological", "balance", 4.2), ("ecological", "system", 4.1),
    ("ecological", "crisis", 4.0), ("biological", "diversity", 4.2),
    ("sea", "level", 4.4), ("water", "quality", 4.2),
    ("air", "quality", 4.3), ("air", "pollution", 4.4),
    ("water", "pollution", 4.2), ("waste", "management", 4.2),
    ("energy", "efficiency", 4.4), ("energy", "consumption", 4.3),
    ("energy", "source", 4.2), ("energy", "transition", 4.1),
    ("solar", "energy", 4.3), ("solar", "panel", 4.2),
    ("wind", "energy", 4.2), ("wind", "farm", 4.1),
    
    # ── Social ──
    ("social", "media", 4.8), ("social", "network", 4.5),
    ("social", "justice", 4.5), ("social", "inequality", 4.4),
    ("social", "change", 4.3), ("social", "impact", 4.3),
    ("social", "responsibility", 4.3), ("social", "norm", 4.2),
    ("social", "structure", 4.2), ("social", "cohesion", 4.1),
    ("social", "welfare", 4.2), ("social", "security", 4.4),
    ("cultural", "heritage", 4.4), ("cultural", "identity", 4.3),
    ("cultural", "diversity", 4.3), ("cultural", "difference", 4.1),
    ("cultural", "value", 4.1), ("cultural", "context", 4.0),
    ("ethnic", "group", 4.2), ("ethnic", "minority", 4.2),
    ("ethnic", "diversity", 4.1), ("racial", "discrimination", 4.3),
    ("racial", "equality", 4.1), ("gender", "equality", 4.4),
    ("gender", "gap", 4.2), ("gender", "difference", 4.1),
    ("income", "inequality", 4.3), ("income", "distribution", 4.2),
    ("poverty", "line", 4.2), ("poverty", "reduction", 4.2),
    ("poverty", "level", 4.1), ("poverty", "rate", 4.1),
    ("population", "growth", 4.3), ("population", "density", 4.2),
    ("population", "aging", 4.1), ("urban", "area", 4.3),
    ("urban", "development", 4.2), ("urban", "planning", 4.2),
    ("rural", "area", 4.3), ("rural", "community", 4.1),
    
    # ── Common phrases / Idioms ──
    ("pros", "cons", 4.3), ("trial", "error", 4.2),
    ("cause", "effect", 4.3), ("supply", "demand", 4.4),
    ("give", "take", 4.0), ("rise", "fall", 4.0),
    ("ups", "downs", 3.9), ("back", "forth", 4.0),
    ("sooner", "later", 4.2), ("now", "then", 3.8),
    ("more", "less", 4.0), ("far", "wide", 3.9),
    ("safe", "sound", 4.1), ("null", "void", 4.2),
    ("peace", "mind", 4.1), ("state", "affairs", 4.1),
    ("point", "view", 4.4), ("frame", "reference", 4.1),
    ("food", "thought", 4.0), ("matter", "fact", 4.2),
    ("means", "end", 4.0), ("long", "run", 4.3),
    ("short", "term", 4.4), ("long", "term", 4.5),
    ("best", "practice", 4.4), ("worst", "case", 4.2),
    ("best", "interest", 4.2), ("greater", "good", 4.1),
    ("added", "value", 4.1), ("vested", "interest", 4.2),
    ("bottom", "line", 4.2), ("turning", "point", 4.3),
    ("last", "resort", 4.3), ("last", "minute", 4.1),
    ("top", "priority", 4.2), ("pressing", "need", 4.1),
    ("pressing", "issue", 4.1), ("pressing", "concern", 4.0),
    ("urgent", "need", 4.2), ("urgent", "matter", 4.0),
    ("burning", "issue", 4.0), ("burning", "question", 4.0),
    ("bone", "contention", 4.1), ("root", "cause", 4.4),
    ("core", "value", 4.2), ("core", "principle", 4.1),
    ("core", "issue", 4.0), ("core", "competency", 4.1),
    ("level", "playing", 4.0), ("playing", "field", 4.2),
]

# ============================================================
# RUSSIAN COLLOCATIONS (~1000+ pairs)
# ============================================================

RU_COLLOCATIONS = [
    # ── Глагол + Существительное ──
    ("принять", "решение", 5.0), ("принять", "меры", 4.8),
    ("принять", "участие", 4.7), ("принять", "закон", 4.5),
    ("принять", "предложение", 4.3), ("принять", "условия", 4.2),
    ("принять", "ответственность", 4.3), ("принять", "вызов", 4.1),
    ("оказать", "влияние", 4.9), ("оказать", "помощь", 4.6),
    ("оказать", "поддержку", 4.5), ("оказать", "воздействие", 4.4),
    ("оказать", "давление", 4.4), ("оказать", "содействие", 4.2),
    ("оказать", "услугу", 4.1), ("оказать", "сопротивление", 4.2),
    ("играть", "роль", 5.0), ("играть", "значение", 4.2),
    ("нести", "ответственность", 4.7), ("нести", "убытки", 4.3),
    ("нести", "потери", 4.3), ("нести", "бремя", 4.1),
    ("иметь", "значение", 4.9), ("иметь", "место", 4.5),
    ("иметь", "право", 4.7), ("иметь", "возможность", 4.6),
    ("иметь", "смысл", 4.4), ("иметь", "представление", 4.2),
    ("иметь", "отношение", 4.3), ("иметь", "опыт", 4.3),
    ("иметь", "доступ", 4.2), ("иметь", "влияние", 4.3),
    ("представлять", "интерес", 4.6), ("представлять", "угрозу", 4.5),
    ("представлять", "опасность", 4.4), ("представлять", "собой", 4.7),
    ("представлять", "отчёт", 4.1), ("представлять", "доказательства", 4.0),
    ("вести", "борьбу", 4.4), ("вести", "переговоры", 4.5),
    ("вести", "деятельность", 4.3), ("вести", "работу", 4.2),
    ("вести", "дискуссию", 4.1), ("вести", "политику", 4.1),
    ("вести", "наблюдение", 4.0), ("вести", "учёт", 4.1),
    ("давать", "возможность", 4.6), ("давать", "ответ", 4.3),
    ("давать", "оценку", 4.3), ("давать", "результат", 4.2),
    ("давать", "показания", 4.2), ("давать", "согласие", 4.1),
    ("достигать", "цели", 4.5), ("достигать", "результата", 4.4),
    ("достигать", "успеха", 4.3), ("достигать", "соглашения", 4.3),
    ("достигать", "уровня", 4.2), ("достигать", "прогресса", 4.1),
    ("ставить", "задачу", 4.4), ("ставить", "цель", 4.4),
    ("ставить", "вопрос", 4.3), ("ставить", "условие", 4.1),
    ("ставить", "проблему", 4.1), ("ставить", "точку", 4.0),
    ("решать", "проблему", 4.6), ("решать", "задачу", 4.5),
    ("решать", "вопрос", 4.4), ("решать", "судьбу", 4.1),
    ("проводить", "исследование", 4.6), ("проводить", "анализ", 4.5),
    ("проводить", "работу", 4.3), ("проводить", "политику", 4.2),
    ("проводить", "реформу", 4.2), ("проводить", "эксперимент", 4.3),
    ("проводить", "опрос", 4.1), ("проводить", "проверку", 4.2),
    ("проводить", "переговоры", 4.1), ("проводить", "мероприятие", 4.1),
    ("обеспечить", "безопасность", 4.5), ("обеспечить", "защиту", 4.4),
    ("обеспечить", "доступ", 4.3), ("обеспечить", "условия", 4.3),
    ("обеспечить", "поддержку", 4.2), ("обеспечить", "выполнение", 4.2),
    ("обеспечить", "стабильность", 4.2), ("обеспечить", "рост", 4.1),
    ("привлечь", "внимание", 4.6), ("привлечь", "инвестиции", 4.3),
    ("привлечь", "интерес", 4.2), ("привлечь", "средства", 4.1),
    ("привлечь", "специалистов", 4.0), ("привлечь", "ресурсы", 3.9),
    ("создать", "условия", 4.4), ("создать", "систему", 4.3),
    ("создать", "основу", 4.2), ("создать", "возможность", 4.2),
    ("создать", "механизм", 4.1), ("создать", "базу", 4.1),
    ("создать", "предпосылки", 4.0), ("создать", "угрозу", 4.0),
    ("установить", "контроль", 4.3), ("установить", "связь", 4.2),
    ("установить", "порядок", 4.1), ("установить", "правила", 4.1),
    ("установить", "факт", 4.1), ("установить", "причину", 4.1),
    ("осуществить", "контроль", 4.2), ("осуществить", "мероприятие", 4.0),
    ("осуществить", "план", 4.0), ("осуществить", "реформу", 4.0),
    ("выполнить", "задачу", 4.3), ("выполнить", "обязательство", 4.2),
    ("выполнить", "требование", 4.2), ("выполнить", "условие", 4.1),
    ("выполнить", "работу", 4.1), ("выполнить", "план", 4.0),
    ("развивать", "сотрудничество", 4.2), ("развивать", "отношения", 4.2),
    ("развивать", "экономику", 4.1), ("развивать", "инфраструктуру", 4.0),
    ("укрепить", "позиции", 4.2), ("укрепить", "безопасность", 4.1),
    ("укрепить", "доверие", 4.1), ("укрепить", "сотрудничество", 4.0),
    ("сохранить", "стабильность", 4.1), ("сохранить", "баланс", 4.0),
    ("сохранить", "мир", 4.0), ("сохранить", "традиции", 3.9),
    ("повысить", "эффективность", 4.3), ("повысить", "качество", 4.3),
    ("повысить", "уровень", 4.2), ("повысить", "производительность", 4.1),
    ("повысить", "конкурентоспособность", 4.1), ("повысить", "ответственность", 4.0),
    ("снизить", "риск", 4.2), ("снизить", "уровень", 4.1),
    ("снизить", "расходы", 4.1), ("снизить", "нагрузку", 4.0),
    ("уменьшить", "риск", 4.1), ("уменьшить", "нагрузку", 4.0),
    ("увеличить", "объём", 4.2), ("увеличить", "производство", 4.1),
    ("увеличить", "долю", 4.0), ("увеличить", "количество", 4.0),
    ("содействовать", "развитию", 4.1), ("содействовать", "укреплению", 4.0),
    ("способствовать", "развитию", 4.3), ("способствовать", "росту", 4.2),
    ("способствовать", "укреплению", 4.1), ("способствовать", "улучшению", 4.0),
    
    # ── Прилагательное + Существительное ──
    ("важный", "роль", 4.8), ("важный", "значение", 4.5),
    ("важный", "фактор", 4.4), ("важный", "аспект", 4.2),
    ("важный", "элемент", 4.2), ("важный", "составляющая", 4.0),
    ("важный", "шаг", 4.1), ("важный", "вклад", 4.0),
    ("большой", "значение", 4.7), ("большой", "внимание", 4.5),
    ("большой", "роль", 4.4), ("большой", "влияние", 4.3),
    ("большой", "интерес", 4.2), ("большой", "опыт", 4.1),
    ("серьёзный", "проблема", 4.5), ("серьёзный", "угроза", 4.3),
    ("серьёзный", "последствия", 4.3), ("серьёзный", "вызов", 4.2),
    ("серьёзный", "ущерб", 4.2), ("серьёзный", "риск", 4.1),
    ("серьёзный", "препятствие", 4.0), ("серьёзный", "опасность", 4.0),
    ("острый", "вопрос", 4.3), ("острый", "проблема", 4.2),
    ("острый", "необходимость", 4.1), ("острый", "нехватка", 4.0),
    ("глубокий", "анализ", 4.4), ("глубокий", "кризис", 4.2),
    ("глубокий", "знания", 4.1), ("глубокий", "понимание", 4.2),
    ("глубокий", "реформа", 4.0), ("глубокий", "изменения", 4.0),
    ("широкий", "круг", 4.5), ("широкий", "спектр", 4.4),
    ("широкий", "масштаб", 4.2), ("широкий", "возможности", 4.1),
    ("широкий", "распространение", 4.1), ("широкий", "охват", 4.0),
    ("ключевой", "фактор", 4.5), ("ключевой", "роль", 4.4),
    ("ключевой", "аспект", 4.2), ("ключевой", "элемент", 4.2),
    ("ключевой", "показатель", 4.1), ("ключевой", "задача", 4.1),
    ("существенный", "влияние", 4.4), ("существенный", "изменения", 4.2),
    ("существенный", "роль", 4.1), ("существенный", "вклад", 4.1),
    ("значительный", "рост", 4.3), ("значительный", "влияние", 4.3),
    ("значительный", "усилия", 4.1), ("значительный", "вклад", 4.2),
    ("значительный", "прогресс", 4.2), ("значительный", "снижение", 4.1),
    ("значительный", "объём", 4.0), ("значительный", "часть", 4.1),
    ("решающий", "роль", 4.4), ("решающий", "значение", 4.2),
    ("решающий", "фактор", 4.2), ("решающий", "момент", 4.1),
    ("критический", "ситуация", 4.2), ("критический", "масса", 4.0),
    ("критический", "уровень", 4.0), ("критический", "момент", 4.0),
    ("основной", "задача", 4.3), ("основной", "причина", 4.2),
    ("основной", "цель", 4.3), ("основной", "принцип", 4.1),
    ("основной", "направление", 4.1), ("основной", "проблема", 4.1),
    ("главный", "задача", 4.2), ("главный", "цель", 4.2),
    ("главный", "причина", 4.1), ("главный", "фактор", 4.1),
    ("первоочередной", "задача", 4.1), ("неотложный", "мера", 4.0),
    ("комплексный", "подход", 4.3), ("комплексный", "решение", 4.1),
    ("комплексный", "мера", 4.0), ("комплексный", "анализ", 4.0),
    ("системный", "подход", 4.2), ("системный", "анализ", 4.0),
    ("системный", "реформа", 3.9), ("стратегический", "цель", 4.2),
    ("стратегический", "план", 4.2), ("стратегический", "направление", 4.1),
    ("стратегический", "задача", 4.0), ("стратегический", "партнёрство", 4.0),
    ("эффективный", "способ", 4.2), ("эффективный", "метод", 4.2),
    ("эффективный", "механизм", 4.1), ("эффективный", "управление", 4.1),
    ("эффективный", "использование", 4.1), ("эффективный", "решение", 4.0),
    ("негативный", "влияние", 4.3), ("негативный", "последствия", 4.3),
    ("негативный", "воздействие", 4.1), ("негативный", "тенденция", 4.0),
    ("позитивный", "влияние", 4.1), ("позитивный", "тенденция", 4.0),
    ("позитивный", "результат", 4.0), ("позитивный", "динамика", 4.0),
    ("устойчивый", "развитие", 4.4), ("устойчивый", "рост", 4.2),
    ("устойчивый", "тенденция", 4.0), ("стремительный", "рост", 4.1),
    ("стремительный", "развитие", 4.0), ("бурный", "рост", 4.0),
    ("резкий", "рост", 4.2), ("резкий", "снижение", 4.1),
    ("резкий", "падение", 4.1), ("резкий", "изменение", 4.0),
    ("постепенный", "рост", 4.0), ("постепенный", "снижение", 3.9),
    ("неуклонный", "рост", 4.0), ("стабильный", "рост", 4.0),
    ("высокий", "уровень", 4.4), ("высокий", "качество", 4.3),
    ("высокий", "степень", 4.2), ("высокий", "темп", 4.1),
    ("высокий", "эффективность", 4.1), ("низкий", "уровень", 4.2),
    ("низкий", "эффективность", 4.0), ("низкий", "качество", 4.0),
    
    # ── Наречия ──
    ("крайне", "важно", 4.5), ("крайне", "необходимо", 4.3),
    ("крайне", "сложно", 4.1), ("крайне", "негативно", 4.0),
    ("весьма", "вероятно", 4.3), ("весьма", "значительный", 4.1),
    ("весьма", "существенный", 4.0), ("весьма", "актуально", 3.9),
    ("чрезвычайно", "важно", 4.4), ("чрезвычайно", "сложно", 4.1),
    ("чрезвычайно", "опасно", 4.0), ("чрезвычайно", "актуально", 3.9),
    ("значительно", "выше", 4.3), ("значительно", "ниже", 4.2),
    ("значительно", "больше", 4.1), ("значительно", "превышать", 4.1),
    ("существенно", "отличаться", 4.3), ("существенно", "влиять", 4.1),
    ("существенно", "снизить", 4.0), ("существенно", "повысить", 4.0),
    ("настоятельно", "рекомендовать", 4.3), ("настоятельно", "необходимо", 4.1),
    ("тесно", "связан", 4.4), ("тесно", "сотрудничать", 4.1),
    ("тесно", "взаимодействовать", 4.0), ("тесно", "переплетаться", 3.9),
    ("активно", "участвовать", 4.3), ("активно", "развивать", 4.1),
    ("активно", "использовать", 4.1), ("активно", "внедрять", 4.0),
    ("активно", "содействовать", 3.9), ("активно", "поддерживать", 4.0),
    ("глубоко", "убеждён", 4.2), ("глубоко", "обеспокоен", 4.1),
    ("глубоко", "изучить", 4.0), ("глубоко", "проникнуть", 3.9),
    ("безусловно", "важно", 4.1), ("безусловно", "необходимо", 4.0),
    ("неизбежно", "привести", 4.0), ("неизбежно", "возникнуть", 3.9),
    ("принципиально", "важно", 4.1), ("принципиально", "новый", 4.0),
    ("всесторонне", "рассмотреть", 4.0), ("всесторонне", "изучить", 3.9),
    ("непосредственно", "влиять", 4.1), ("непосредственно", "связан", 4.2),
    ("последовательно", "проводить", 4.0), ("последовательно", "реализовать", 3.9),
    ("целенаправленно", "работать", 4.0), ("целенаправленно", "развивать", 3.9),
    
    # ── Устойчивые выражения ──
    ("в", "целом", 4.5), ("в", "частности", 4.5),
    ("в", "итоге", 4.3), ("в", "результате", 4.5),
    ("в", "рамках", 4.4), ("в", "условиях", 4.3),
    ("в", "связи", 4.5), ("в", "принципе", 4.1),
    ("в", "основном", 4.3), ("в", "настоящее", 4.4),
    ("по", "мнению", 4.5), ("по", "данным", 4.3),
    ("по", "сравнению", 4.4), ("по", "существу", 4.0),
    ("на", "основе", 4.4), ("на", "практике", 4.2),
    ("на", "уровне", 4.2), ("на", "первый", 4.1),
    ("с", "учётом", 4.3), ("с", "целью", 4.2),
    ("с", "точки", 4.4), ("точки", "зрения", 4.5),
    ("таким", "образом", 4.8), ("вместе", "тем", 4.5),
    ("прежде", "всего", 4.5), ("тем", "менее", 4.5),
    ("более", "того", 4.5), ("кроме", "того", 4.5),
    ("помимо", "этого", 4.2), ("между", "тем", 4.3),
    ("само", "собой", 4.0), ("так", "называемый", 4.1),
    ("тот", "факт", 4.2), ("речь", "идёт", 4.3),
    ("другими", "словами", 4.2), ("иными", "словами", 4.1),
    ("одним", "словом", 4.0), ("обратить", "внимание", 4.5),
    ("следует", "отметить", 4.4), ("необходимо", "отметить", 4.3),
    ("стоит", "отметить", 4.2), ("нельзя", "забывать", 4.0),
    ("нельзя", "игнорировать", 4.0), ("нельзя", "недооценивать", 4.0),
    
    # ── Тематические: экономика, политика, наука ──
    ("экономический", "рост", 4.5), ("экономический", "развитие", 4.4),
    ("экономический", "кризис", 4.4), ("экономический", "политика", 4.3),
    ("экономический", "эффективность", 4.1), ("экономический", "реформа", 4.1),
    ("экономический", "стабильность", 4.0), ("экономический", "ситуация", 4.0),
    ("социальный", "защита", 4.3), ("социальный", "политика", 4.3),
    ("социальный", "обеспечение", 4.2), ("социальный", "справедливость", 4.1),
    ("социальный", "сфера", 4.1), ("социальный", "проблема", 4.0),
    ("политический", "система", 4.3), ("политический", "партия", 4.3),
    ("политический", "кризис", 4.2), ("политический", "стабильность", 4.1),
    ("политический", "реформа", 4.1), ("политический", "решение", 4.0),
    ("государственный", "управление", 4.3), ("государственный", "политика", 4.2),
    ("государственный", "бюджет", 4.2), ("государственный", "регулирование", 4.1),
    ("международный", "сотрудничество", 4.3), ("международный", "отношения", 4.3),
    ("международный", "организация", 4.2), ("международный", "безопасность", 4.1),
    ("международный", "опыт", 4.0), ("международный", "право", 4.1),
    ("научный", "исследование", 4.4), ("научный", "метод", 4.2),
    ("научный", "подход", 4.2), ("научный", "открытие", 4.1),
    ("научный", "знание", 4.0), ("научный", "деятельность", 4.0),
    ("информационный", "технология", 4.3), ("информационный", "система", 4.1),
    ("информационный", "безопасность", 4.1), ("информационный", "поле", 3.9),
]

# ============================================================
# GERMAN COLLOCATIONS (~500+ pairs)
# ============================================================

DE_COLLOCATIONS = [
    ("eine", "rolle", 4.8), ("große", "rolle", 4.7),
    ("wichtige", "rolle", 4.6), ("entscheidende", "rolle", 4.5),
    ("zentrale", "rolle", 4.4), ("bedeutende", "rolle", 4.3),
    ("eine", "entscheidung", 4.6), ("eine", "lösung", 4.3),
    ("einen", "beitrag", 4.3), ("einen", "einfluss", 4.2),
    ("maßnahmen", "ergreifen", 4.6), ("maßnahmen", "treffen", 4.4),
    ("zur", "verfügung", 4.8), ("in", "betracht", 4.5),
    ("in", "frage", 4.5), ("in", "anspruch", 4.3),
    ("in", "bezug", 4.4), ("in", "kraft", 4.3),
    ("auswirkungen", "haben", 4.4), ("einfluss", "nehmen", 4.4),
    ("einfluss", "haben", 4.3), ("einfluss", "ausüben", 4.3),
    ("beitrag", "leisten", 4.4), ("verantwortung", "tragen", 4.5),
    ("verantwortung", "übernehmen", 4.4),
    ("bedeutung", "haben", 4.5), ("bedeutung", "gewinnen", 4.2),
    ("aufmerksamkeit", "schenken", 4.3), ("aufmerksamkeit", "erregen", 4.2),
    ("äußerst", "wichtig", 4.3), ("besonders", "wichtig", 4.4),
    ("überaus", "wichtig", 4.1), ("dringend", "notwendig", 4.2),
    ("eng", "verbunden", 4.3), ("eng", "zusammenarbeiten", 4.2),
    ("eng", "verknüpft", 4.1), ("stark", "betroffen", 4.2),
    ("stark", "beeinflusst", 4.1), ("stark", "abhängig", 4.1),
    ("weit", "verbreitet", 4.3), ("weit", "entfernt", 3.9),
    ("deutlich", "höher", 4.2), ("deutlich", "geringer", 4.0),
    ("deutlich", "gestiegen", 4.1), ("deutlich", "verbessert", 4.0),
    ("erheblich", "steigern", 4.1), ("erheblich", "verbessern", 4.1),
    ("erheblich", "beeinträchtigen", 4.0), ("erheblich", "beitragen", 3.9),
    ("wesentlich", "beitragen", 4.1), ("wesentlich", "verbessern", 4.0),
    ("maßgeblich", "beitragen", 4.0), ("maßgeblich", "beeinflusst", 4.0),
    ("nachhaltig", "entwicklung", 4.3), ("nachhaltig", "wachstum", 4.1),
    ("nachhaltig", "nutzen", 4.0), ("nachhaltig", "wirtschaften", 3.9),
    ("wirtschaftlich", "wachstum", 4.3), ("wirtschaftlich", "entwicklung", 4.2),
    ("wirtschaftlich", "lage", 4.1), ("wirtschaftlich", "krise", 4.1),
    ("politisch", "system", 4.2), ("politisch", "stabilität", 4.1),
    ("politisch", "partei", 4.2), ("politisch", "entscheidung", 4.0),
    ("sozial", "gerechtigkeit", 4.2), ("sozial", "sicherheit", 4.2),
    ("sozial", "verantwortung", 4.1), ("sozial", "ungleichheit", 4.0),
    ("öffentlich", "meinung", 4.3), ("öffentlich", "interesse", 4.2),
    ("öffentlich", "dienst", 4.1), ("öffentlich", "haushalt", 4.0),
    ("gesetzlich", "regelung", 4.2), ("gesetzlich", "grundlage", 4.1),
    ("gesetzlich", "vorschrift", 4.0), ("gesetzlich", "rahmen", 4.0),
    ("grundlegend", "veränderung", 4.1), ("grundlegend", "reform", 4.1),
    ("grundlegend", "prinzip", 4.0), ("grundlegend", "recht", 4.1),
    ("hoher", "qualität", 4.2), ("hoher", "maß", 4.1),
    ("in", "erster", 4.1), ("erster", "linie", 4.3),
    ("vor", "allem", 4.5), ("nach", "wie", 4.2),
    ("im", "grunde", 4.1), ("im", "wesentlichen", 4.2),
    ("im", "rahmen", 4.3), ("im", "zusammenhang", 4.2),
    ("zum", "beispiel", 4.5), ("zum", "teil", 4.2),
    ("zum", "ausdruck", 4.1), ("zum", "schluss", 4.0),
    ("unter", "berücksichtigung", 4.1), ("unter", "anderem", 4.2),
    ("auf", "grundlage", 4.1), ("auf", "basis", 4.0),
    # Technology
    ("künstlich", "intelligenz", 4.6), ("maschinell", "lernen", 4.3),
    ("erneuerbar", "energie", 4.4), ("digital", "transformation", 4.3),
    ("digital", "technologie", 4.1), ("klimawandel", "bekämpfen", 4.0),
    # Health
    ("psychisch", "gesundheit", 4.3), ("körperlich", "gesundheit", 4.1),
    ("klinisch", "studie", 4.2), ("chronisch", "krankheit", 4.1),
    ("öffentlich", "gesundheit", 4.2), ("gesundheitlich", "versorgung", 4.0),
    # Verbs
    ("berücksichtigung", "finden", 4.0), ("anwendung", "finden", 4.1),
    ("stellung", "nehmen", 4.1), ("rechnung", "tragen", 4.1),
    ("punkt", "bringen", 4.0), ("frage", "stellen", 4.2),
    ("antwort", "geben", 4.0), ("problem", "lösen", 4.2),
    ("ziel", "erreichen", 4.2), ("ergebnis", "erzielen", 4.1),
    ("fortschritt", "erzielen", 4.0), ("erfolg", "haben", 4.1),
    ("sinn", "machen", 4.0), ("mühe", "machen", 3.9),
]

# ============================================================
# FRENCH COLLOCATIONS (~500+ pairs)
# ============================================================

FR_COLLOCATIONS = [
    ("jouer", "rôle", 4.8), ("rôle", "important", 4.6),
    ("rôle", "crucial", 4.4), ("rôle", "clé", 4.3),
    ("rôle", "essentiel", 4.3), ("rôle", "majeur", 4.2),
    ("prendre", "décision", 4.7), ("prendre", "mesure", 4.5),
    ("prendre", "conscience", 4.4), ("prendre", "compte", 4.6),
    ("prendre", "part", 4.3), ("prendre", "initiative", 4.2),
    ("prendre", "position", 4.1), ("prendre", "engagement", 4.0),
    ("avoir", "lieu", 4.8), ("avoir", "impact", 4.4),
    ("avoir", "effet", 4.3), ("avoir", "tendance", 4.2),
    ("avoir", "accès", 4.3), ("avoir", "droit", 4.3),
    ("avoir", "intérêt", 4.1), ("avoir", "sens", 4.1),
    ("mettre", "place", 4.7), ("mettre", "oeuvre", 4.6),
    ("mettre", "évidence", 4.4), ("mettre", "disposition", 4.3),
    ("mettre", "valeur", 4.2), ("mettre", "accent", 4.1),
    ("rendre", "compte", 4.6), ("rendre", "possible", 4.2),
    ("rendre", "service", 4.0), ("rendre", "justice", 3.9),
    ("tenir", "compte", 4.7), ("tenir", "rôle", 4.2),
    ("tenir", "promesse", 4.0), ("faire", "preuve", 4.5),
    ("faire", "face", 4.4), ("faire", "partie", 4.5),
    ("faire", "objet", 4.3), ("faire", "appel", 4.2),
    ("faire", "valoir", 4.1), ("faire", "remarquer", 4.0),
    ("porter", "attention", 4.5), ("porter", "fruit", 4.1),
    ("porter", "atteinte", 4.2), ("porter", "intérêt", 4.0),
    ("grande", "importance", 4.5), ("grande", "majorité", 4.4),
    ("grande", "partie", 4.3), ("grande", "mesure", 4.2),
    ("grande", "ampleur", 4.1), ("grand", "nombre", 4.3),
    ("extrêmement", "important", 4.3), ("extrêmement", "difficile", 4.1),
    ("extrêmement", "complexe", 4.0), ("extrêmement", "dangereux", 3.9),
    ("fortement", "recommandé", 4.3), ("fortement", "influencé", 4.1),
    ("fortement", "contesté", 4.0), ("fortement", "critiqué", 4.0),
    ("étroitement", "lié", 4.3), ("étroitement", "associé", 4.1),
    ("étroitement", "collaborer", 4.0), ("étroitement", "surveillé", 3.9),
    ("largement", "utilisé", 4.3), ("largement", "répandu", 4.2),
    ("largement", "reconnu", 4.1), ("largement", "accepté", 4.0),
    ("profondément", "convaincu", 4.1), ("profondément", "marqué", 4.0),
    ("profondément", "ancré", 4.0), ("profondément", "affecté", 3.9),
    # Academic / Research
    ("recherche", "scientifique", 4.3), ("étude", "approfondie", 4.1),
    ("analyse", "approfondie", 4.2), ("données", "empiriques", 4.1),
    ("résultat", "concluant", 4.0), ("approche", "méthodologique", 4.0),
    ("cadre", "théorique", 4.1), ("contribuer", "développement", 4.1),
    ("contribuer", "amélioration", 4.0), ("favoriser", "développement", 4.0),
    # Economy
    ("croissance", "économique", 4.4), ("développement", "durable", 4.5),
    ("politique", "économique", 4.2), ("réforme", "structurelle", 4.1),
    ("marché", "financier", 4.2), ("crise", "économique", 4.3),
    ("investissement", "étranger", 4.1), ("secteur", "privé", 4.2),
    ("secteur", "public", 4.2), ("service", "public", 4.3),
    # Social
    ("justice", "sociale", 4.3), ("protection", "sociale", 4.3),
    ("cohésion", "sociale", 4.1), ("dialogue", "social", 4.0),
    ("politique", "sociale", 4.1), ("changement", "climatique", 4.4),
    ("transition", "écologique", 4.2), ("énergie", "renouvelable", 4.3),
    # Expressions
    ("au", "sein", 4.3), ("en", "effet", 4.4),
    ("en", "revanche", 4.2), ("en", "outre", 4.3),
    ("en", "particulier", 4.3), ("en", "raison", 4.3),
    ("en", "matière", 4.2), ("en", "dépit", 4.1),
    ("en", "vue", 4.1), ("en", "faveur", 4.1),
    ("par", "conséquent", 4.3), ("par", "ailleurs", 4.3),
    ("par", "rapport", 4.4), ("par", "exemple", 4.5),
    ("tout", "fait", 4.2), ("tout", "cas", 4.1),
    ("bien", "entendu", 4.1), ("bien", "sûr", 4.2),
    ("il", "convient", 4.1), ("il", "importe", 4.0),
    ("il", "ressort", 3.9), ("il", "apparaît", 4.0),
    ("mise", "oeuvre", 4.5), ("prise", "compte", 4.4),
    ("point", "vue", 4.4), ("mesure", "nécessaire", 4.0),
    ("résultat", "obtenu", 4.0), ("objectif", "fixé", 4.0),
]

# ============================================================
# SPANISH COLLOCATIONS (~500+ pairs)
# ============================================================

ES_COLLOCATIONS = [
    ("tomar", "decisión", 4.7), ("tomar", "medida", 4.5),
    ("tomar", "conciencia", 4.2), ("tomar", "iniciativa", 4.1),
    ("tomar", "posición", 4.0), ("tomar", "parte", 4.0),
    ("desempeñar", "papel", 4.5), ("desempeñar", "función", 4.2),
    ("desempeñar", "rol", 4.1), ("desempeñar", "cargo", 4.0),
    ("tener", "lugar", 4.8), ("tener", "derecho", 4.5),
    ("tener", "sentido", 4.3), ("tener", "acceso", 4.2),
    ("tener", "impacto", 4.2), ("tener", "efecto", 4.2),
    ("tener", "cuenta", 4.5), ("tener", "presente", 4.1),
    ("poner", "marcha", 4.5), ("poner", "manifiesto", 4.3),
    ("poner", "práctica", 4.2), ("poner", "disposición", 4.1),
    ("poner", "relieve", 4.1), ("poner", "riesgo", 4.0),
    ("prestar", "atención", 4.6), ("prestar", "servicio", 4.2),
    ("prestar", "apoyo", 4.1), ("prestar", "ayuda", 4.0),
    ("llevar", "cabo", 4.8), ("llevar", "término", 4.1),
    ("llevar", "práctica", 4.0), ("dar", "lugar", 4.3),
    ("dar", "cuenta", 4.2), ("dar", "paso", 4.1),
    ("dar", "respuesta", 4.1), ("dar", "resultado", 4.0),
    ("hacer", "frente", 4.3), ("hacer", "hincapié", 4.2),
    ("hacer", "referencia", 4.2), ("hacer", "énfasis", 4.0),
    ("gran", "importancia", 4.5), ("gran", "parte", 4.4),
    ("gran", "medida", 4.4), ("gran", "número", 4.3),
    ("gran", "mayoría", 4.3), ("gran", "escala", 4.1),
    ("gran", "impacto", 4.1), ("gran", "alcance", 4.1),
    ("sumamente", "importante", 4.3), ("sumamente", "difícil", 4.0),
    ("altamente", "competitivo", 4.1), ("altamente", "calificado", 4.0),
    ("estrechamente", "vinculado", 4.2), ("estrechamente", "relacionado", 4.2),
    ("estrechamente", "ligado", 4.0), ("estrechamente", "asociado", 4.0),
    ("ampliamente", "utilizado", 4.3), ("ampliamente", "reconocido", 4.2),
    ("ampliamente", "aceptado", 4.1), ("ampliamente", "difundido", 4.0),
    ("profundamente", "convencido", 4.1), ("profundamente", "afectado", 4.0),
    ("profundamente", "arraigado", 4.0), ("profundamente", "comprometido", 3.9),
    ("significativamente", "mayor", 4.2), ("significativamente", "menor", 4.1),
    ("considerablemente", "mayor", 4.0), ("considerablemente", "menor", 3.9),
    ("papel", "importante", 4.6), ("papel", "fundamental", 4.4),
    ("papel", "crucial", 4.3), ("papel", "clave", 4.3),
    ("factor", "clave", 4.5), ("factor", "determinante", 4.3),
    ("factor", "importante", 4.1), ("factor", "decisivo", 4.1),
    ("cambio", "climático", 4.6), ("desarrollo", "sostenible", 4.5),
    ("crecimiento", "económico", 4.4), ("política", "pública", 4.3),
    ("política", "económica", 4.2), ("política", "social", 4.2),
    ("organización", "internacional", 4.2), ("comunidad", "internacional", 4.3),
    ("derechos", "humanos", 4.7), ("derecho", "internacional", 4.3),
    ("sociedad", "civil", 4.3), ("sector", "público", 4.2),
    ("sector", "privado", 4.2), ("servicio", "público", 4.2),
    ("sistema", "educativo", 4.2), ("sistema", "político", 4.1),
    ("marco", "legal", 4.2), ("marco", "jurídico", 4.1),
    ("marco", "regulatorio", 4.0), ("marco", "institucional", 4.0),
    ("en", "consecuencia", 4.3), ("en", "particular", 4.4),
    ("por", "tanto", 4.4), ("por", "consiguiente", 4.2),
    ("por", "ejemplo", 4.5), ("sin", "embargo", 4.7),
    ("no", "obstante", 4.4), ("al", "respecto", 4.1),
    ("al", "mismo", 4.2), ("así", "como", 4.2),
    ("en", "relación", 4.2), ("en", "cuanto", 4.2),
    ("en", "materia", 4.1), ("en", "virtud", 4.0),
    ("con", "respecto", 4.2), ("con", "fin", 4.1),
    ("con", "objeto", 4.0), ("de", "acuerdo", 4.3),
    ("punto", "vista", 4.4), ("medio", "ambiente", 4.5),
    # Science / Tech
    ("inteligencia", "artificial", 4.5), ("aprendizaje", "automático", 4.2),
    ("transformación", "digital", 4.2), ("energía", "renovable", 4.4),
    # Health
    ("salud", "pública", 4.4), ("salud", "mental", 4.3),
    ("atención", "médica", 4.2), ("sistema", "salud", 4.1),
    ("ensayo", "clínico", 4.1), ("efecto", "adverso", 4.0),
]

# ============================================================
# ITALIAN COLLOCATIONS
# ============================================================

IT_COLLOCATIONS = [
    ("svolgere", "ruolo", 4.5), ("ruolo", "importante", 4.4),
    ("ruolo", "cruciale", 4.2), ("ruolo", "fondamentale", 4.3),
    ("prendere", "decisione", 4.4), ("prendere", "misura", 4.2),
    ("prendere", "coscienza", 4.0), ("avere", "luogo", 4.5),
    ("avere", "impatto", 4.2), ("avere", "effetto", 4.2),
    ("avere", "senso", 4.1), ("avere", "diritto", 4.3),
    ("mettere", "pratica", 4.2), ("mettere", "evidenza", 4.1),
    ("mettere", "atto", 4.2), ("tenere", "conto", 4.5),
    ("tenere", "presente", 4.1), ("fare", "fronte", 4.2),
    ("fare", "parte", 4.3), ("fare", "riferimento", 4.2),
    ("prestare", "attenzione", 4.4), ("grande", "importanza", 4.4),
    ("grande", "maggioranza", 4.2), ("grande", "numero", 4.1),
    ("sviluppo", "sostenibile", 4.4), ("crescita", "economica", 4.3),
    ("cambiamento", "climatico", 4.4), ("energia", "rinnovabile", 4.2),
    ("in", "particolare", 4.3), ("per", "quanto", 4.1),
    ("al", "fine", 4.1), ("in", "merito", 4.0),
    ("punto", "vista", 4.3), ("in", "relazione", 4.0),
    ("in", "materia", 4.0), ("a", "causa", 4.1),
    ("di", "conseguenza", 4.1), ("per", "esempio", 4.4),
]

# ============================================================
# PORTUGUESE COLLOCATIONS
# ============================================================

PT_COLLOCATIONS = [
    ("desempenhar", "papel", 4.5), ("papel", "importante", 4.4),
    ("papel", "fundamental", 4.3), ("tomar", "decisão", 4.4),
    ("tomar", "medida", 4.2), ("ter", "lugar", 4.5),
    ("ter", "impacto", 4.2), ("ter", "efeito", 4.1),
    ("ter", "direito", 4.3), ("ter", "acesso", 4.1),
    ("fazer", "parte", 4.3), ("fazer", "frente", 4.1),
    ("fazer", "referência", 4.0), ("prestar", "atenção", 4.3),
    ("levar", "consideração", 4.2), ("levar", "conta", 4.3),
    ("levar", "cabo", 4.1), ("grande", "importância", 4.4),
    ("grande", "maioria", 4.2), ("grande", "número", 4.1),
    ("desenvolvimento", "sustentável", 4.4), ("crescimento", "económico", 4.3),
    ("mudança", "climática", 4.3), ("energia", "renovável", 4.2),
    ("direitos", "humanos", 4.5), ("saúde", "pública", 4.3),
    ("saúde", "mental", 4.1), ("no", "entanto", 4.5),
    ("por", "exemplo", 4.4), ("em", "relação", 4.2),
    ("em", "particular", 4.2), ("de", "acordo", 4.2),
    ("ponto", "vista", 4.3), ("por", "conseguinte", 4.0),
    ("tendo", "conta", 4.0), ("nesse", "sentido", 3.9),
]

# ============================================================
# POLISH COLLOCATIONS
# ============================================================

PL_COLLOCATIONS = [
    ("odgrywać", "rolę", 4.5), ("ważna", "rola", 4.4),
    ("kluczowa", "rola", 4.3), ("podjąć", "decyzję", 4.4),
    ("podjąć", "działania", 4.2), ("podjąć", "kroki", 4.1),
    ("mieć", "znaczenie", 4.5), ("mieć", "wpływ", 4.4),
    ("mieć", "miejsce", 4.3), ("mieć", "prawo", 4.2),
    ("mieć", "dostęp", 4.1), ("mieć", "sens", 4.0),
    ("zwracać", "uwagę", 4.3), ("brać", "udział", 4.3),
    ("brać", "odpowiedzialność", 4.1), ("prowadzić", "działalność", 4.1),
    ("prowadzić", "badania", 4.2), ("prowadzić", "politykę", 4.0),
    ("duże", "znaczenie", 4.3), ("wielki", "znaczenie", 4.1),
    ("poważny", "problem", 4.2), ("poważne", "zagrożenie", 4.0),
    ("istotny", "wpływ", 4.1), ("istotna", "rola", 4.1),
    ("w", "wyniku", 4.2), ("w", "ramach", 4.3),
    ("w", "szczególności", 4.3), ("na", "przykład", 4.4),
    ("ze", "względu", 4.2), ("w", "związku", 4.2),
    ("między", "innymi", 4.2), ("przede", "wszystkim", 4.3),
    ("punkt", "widzenia", 4.3), ("w", "istocie", 4.0),
]

# ============================================================
# UKRAINIAN COLLOCATIONS
# ============================================================

UK_COLLOCATIONS = [
    ("відігравати", "роль", 4.5), ("важлива", "роль", 4.4),
    ("ключова", "роль", 4.3), ("прийняти", "рішення", 4.5),
    ("прийняти", "заходи", 4.2), ("прийняти", "участь", 4.3),
    ("мати", "значення", 4.5), ("мати", "вплив", 4.4),
    ("мати", "місце", 4.2), ("мати", "право", 4.3),
    ("мати", "доступ", 4.1), ("мати", "можливість", 4.3),
    ("звертати", "увагу", 4.3), ("привертати", "увагу", 4.2),
    ("брати", "участь", 4.4), ("нести", "відповідальність", 4.3),
    ("проводити", "дослідження", 4.3), ("проводити", "аналіз", 4.1),
    ("забезпечити", "безпеку", 4.2), ("забезпечити", "захист", 4.1),
    ("велике", "значення", 4.3), ("суттєвий", "вплив", 4.1),
    ("значний", "вплив", 4.1), ("серйозна", "проблема", 4.1),
    ("в", "результаті", 4.2), ("в", "рамках", 4.2),
    ("зокрема", "щодо", 3.9), ("наприклад", "можна", 3.8),
    ("з", "точки", 4.0), ("точки", "зору", 4.3),
    ("таким", "чином", 4.5), ("разом", "тим", 4.2),
    ("крім", "того", 4.3), ("перш", "все", 4.2),
    ("сталий", "розвиток", 4.3), ("економічне", "зростання", 4.2),
    ("зміна", "клімату", 4.1), ("права", "людини", 4.4),
]

ALL_LANGS = {
    "en": EN_COLLOCATIONS,
    "ru": RU_COLLOCATIONS,
    "de": DE_COLLOCATIONS,
    "fr": FR_COLLOCATIONS,
    "es": ES_COLLOCATIONS,
    "it": IT_COLLOCATIONS,
    "pt": PT_COLLOCATIONS,
    "pl": PL_COLLOCATIONS,
    "uk": UK_COLLOCATIONS,
}


def compress_lang(triplets: list[tuple[str, str, float]]) -> str:
    """Compress list of (w1, w2, pmi) to base64 string."""
    # Deduplicate
    seen = set()
    unique = []
    for w1, w2, pmi in triplets:
        key = (w1.lower(), w2.lower())
        if key not in seen:
            seen.add(key)
            unique.append((w1.lower(), w2.lower(), pmi))
    
    lines = []
    for w1, w2, pmi in unique:
        lines.append(f"{w1}\t{w2}\t{pmi:.1f}")
    
    raw = "\n".join(lines).encode("utf-8")
    compressed = zlib.compress(raw, 9)
    b64 = base64.b64encode(compressed).decode("ascii")
    return b64, len(unique)


def main():
    buf = io.StringIO()
    buf.write('"""Auto-generated collocation data. DO NOT EDIT.\n\n')
    buf.write('Generated by scripts/gen_collocations.py\n')
    buf.write('"""\n\nfrom __future__ import annotations\n\n')
    buf.write('import base64\nimport zlib\n')
    buf.write('from typing import Dict, Tuple\n\n')
    
    # Write compressed data
    total = 0
    for lang, data in ALL_LANGS.items():
        b64, count = compress_lang(data)
        total += count
        wrapped = textwrap.fill(b64, width=76)
        buf.write(f"_{lang.upper()}_DATA = (\n")
        for line in wrapped.split("\n"):
            buf.write(f'    "{line}"\n')
        buf.write(f")  # {count} pairs\n\n")
    
    # Write decoder
    buf.write("""
_cache: dict[str, dict[tuple[str, str], float]] = {}

def _decode(b64: str) -> dict[tuple[str, str], float]:
    raw = zlib.decompress(base64.b64decode(b64)).decode("utf-8")
    result: dict[tuple[str, str], float] = {}
    for line in raw.split("\\n"):
        if not line:
            continue
        parts = line.split("\\t")
        if len(parts) == 3:
            result[(parts[0], parts[1])] = float(parts[2])
    return result

""")
    
    # Write getters
    for lang in ALL_LANGS:
        upper = lang.upper()
        buf.write(f"def get_{lang}_collocations() -> dict[tuple[str, str], float]:\n")
        buf.write(f'    if "{lang}" not in _cache:\n')
        buf.write(f'        _cache["{lang}"] = _decode(_{upper}_DATA)\n')
        buf.write(f'    return _cache["{lang}"]\n\n')
    
    # Write combined getter
    buf.write("\n_LANG_GETTERS = {\n")
    for lang in ALL_LANGS:
        buf.write(f'    "{lang}": get_{lang}_collocations,\n')
    buf.write("}\n\n\n")
    buf.write("def get_collocations(lang: str) -> dict[tuple[str, str], float]:\n")
    buf.write('    getter = _LANG_GETTERS.get(lang)\n')
    buf.write('    if getter:\n')
    buf.write('        return getter()\n')
    buf.write('    return {}\n')
    
    outpath = "texthumanize/_colloc_data.py"
    with open(outpath, "w", encoding="utf-8") as f:
        f.write(buf.getvalue())
    
    print(f"Generated {outpath}: {total} total collocations")
    for lang, data in ALL_LANGS.items():
        _, count = compress_lang(data)
        print(f"  {lang}: {count}")


if __name__ == "__main__":
    main()
